{
  "hash": "51acacbefde3671a06848c744eabcdfd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Chen Yitao\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\ncensus_api_key(Sys.getenv(\"CENSUS_API_KEY\"))\n# Load spatial data\npa_counties <- st_read(here(\"C:/Users/cheny/Desktop/CPLN 5920 Public Policy Analytics/CPLN-5920-SP26-main/CPLN-5920-SP26-main/lectures/week_04/data/Pennsylvania_County_Boundaries.shp\"))\nhospitals <- st_read(here(\"C:/Users/cheny/Desktop/CPLN 5920 Public Policy Analytics/CPLN-5920-SP26-main/CPLN-5920-SP26-main/lectures/week_04/data/hospitals.geojson\"))\ncensus_tracts <- tracts(state = \"PA\", cb = TRUE)\n# Check that all data loaded correctly\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\nglimpse(pa_counties)\nglimpse(hospitals)\nglimpse(census_tracts)\n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset? Hospitals: 223 \n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Hospitals:\", nrow(hospitals), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHospitals: 223 \n```\n\n\n:::\n:::\n\n\n- How many census tracts? Number of census tracts: 3445 \n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Number of census tracts:\", nrow(census_tracts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of census tracts: 3445 \n```\n\n\n:::\n:::\n\n\n- What coordinate reference system is each dataset in? \"WGS 84 / Pseudo-Mercator\"\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(pa_counties)\nst_crs(hospitals)\nst_crs(census_tracts)\n```\n:::\n\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\ntract_demographics <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\",\n    male_65_66 = \"B01001_020\",\n    male_67_69 = \"B01001_021\",\n    male_70_74 = \"B01001_022\",\n    male_75_79 = \"B01001_023\",\n    male_80_84 = \"B01001_024\",\n    male_85_up = \"B01001_025\",\n    female_65_66 = \"B01001_044\",\n    female_67_69 = \"B01001_045\",\n    female_70_74 = \"B01001_046\",\n    female_75_79 = \"B01001_047\",\n    female_80_84 = \"B01001_048\",\n    female_85_up = \"B01001_049\"),\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"\n)\n\ntract_demographics <- tract_demographics %>%\n  mutate(\n    over_65E =\n      male_65_66E + male_67_69E + male_70_74E + male_75_79E + male_80_84E + male_85_upE +\n      female_65_66E + female_67_69E + female_70_74E + female_75_79E + female_80_84E + female_85_upE,\n    over_65M = sqrt(\n      male_65_66M^2 + male_67_69M^2 + male_70_74M^2 + male_75_79M^2 + male_80_84M^2 + male_85_upM^2 +\n      female_65_66M^2 + female_67_69M^2 + female_70_74M^2 + female_75_79M^2 + female_80_84M^2 + female_85_upM^2\n    )\n )\n\ntract_demographics_sum <- tract_demographics %>%\n  select(\n    GEOID,\n    total_popE, total_popM,\n    median_incomeE, median_incomeM,\n    over_65E, over_65M\n  )\nglimpse(tract_demographics_sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,446\nColumns: 7\n$ GEOID          <chr> \"42001030101\", \"42001030103\", \"42001030104\", \"420010302…\n$ total_popE     <dbl> 2658, 2416, 3395, 5475, 4412, 5462, 3782, 4879, 6541, 3…\n$ total_popM     <dbl> 14, 329, 332, 464, 215, 206, 221, 22, 375, 322, 136, 18…\n$ median_incomeE <dbl> 80231, 111603, 81150, 68363, 81577, 88558, 62652, 76250…\n$ median_incomeM <dbl> 12428, 13757, 37724, 3192, 6735, 15104, 7818, 11464, 78…\n$ over_65E       <dbl> 521, 467, 730, 1020, 722, 1206, 806, 1213, 1173, 652, 3…\n$ over_65M       <dbl> 111.79893, 228.96288, 199.70478, 180.21654, 153.72378, …\n```\n\n\n:::\n\n```{.r .cell-code}\n# Join to tract boundaries\ncensus_tracts_join <- census_tracts %>%\n  left_join(tract_demographics_sum, by = \"GEOID\")\n\nglimpse(census_tracts_join)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,445\nColumns: 20\n$ STATEFP        <chr> \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"42\", \"…\n$ COUNTYFP       <chr> \"001\", \"013\", \"013\", \"013\", \"013\", \"011\", \"011\", \"011\",…\n$ TRACTCE        <chr> \"031101\", \"100400\", \"100500\", \"100800\", \"101900\", \"0112…\n$ GEOIDFQ        <chr> \"1400000US42001031101\", \"1400000US42013100400\", \"140000…\n$ GEOID          <chr> \"42001031101\", \"42013100400\", \"42013100500\", \"420131008…\n$ NAME           <chr> \"311.01\", \"1004\", \"1005\", \"1008\", \"1019\", \"112\", \"2\", \"…\n$ NAMELSAD       <chr> \"Census Tract 311.01\", \"Census Tract 1004\", \"Census Tra…\n$ STUSPS         <chr> \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"…\n$ NAMELSADCO     <chr> \"Adams County\", \"Blair County\", \"Blair County\", \"Blair …\n$ STATE_NAME     <chr> \"Pennsylvania\", \"Pennsylvania\", \"Pennsylvania\", \"Pennsy…\n$ LSAD           <chr> \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"CT\", \"…\n$ ALAND          <dbl> 3043185, 993724, 1130204, 996553, 573726, 1539365, 1949…\n$ AWATER         <dbl> 0, 0, 0, 0, 0, 9308, 159015, 12469, 0, 0, 0, 1271, 6352…\n$ total_popE     <dbl> 5070, 1589, 3380, 1860, 1436, 4533, 4318, 2923, 3936, 1…\n$ total_popM     <dbl> 358, 253, 580, 256, 196, 19, 678, 16, 456, 368, 644, 30…\n$ median_incomeE <dbl> 61847, 67120, 50450, 64583, 16429, 56818, 23424, 76410,…\n$ median_incomeM <dbl> 8600, 12405, 5089, 19957, 2414, 7404, 5240, 5720, 17377…\n$ over_65E       <dbl> 946, 238, 463, 282, 636, 600, 617, 500, 487, 375, 1658,…\n$ over_65M       <dbl> 250.30182, 90.16651, 105.41347, 77.56932, 157.65151, 13…\n$ geometry       <MULTIPOLYGON [m]> MULTIPOLYGON (((-8575060 48..., MULTIPOLYG…\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using? 2022\n- How many tracts have missing income data? 62\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\n  \"Tracts with missing income data:\",\n  sum(is.na(census_tracts_join$median_incomeE)),\n  \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTracts with missing income data: 62 \n```\n\n\n:::\n:::\n\n- What is the median income across all PA census tracts? 70188\t\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian_income_all <- census_tracts_join %>%\n  st_drop_geometry() %>%\n  summarize(\n    median_income = median(median_incomeE, na.rm = TRUE)\n  )\nmedian_income_all\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  median_income\n1         70188\n```\n\n\n:::\n:::\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\ncriteria_tracts <- census_tracts_join %>%\n  mutate(pct_over_65 = over_65E / total_popE * 100) %>%\n  filter(\n    !is.na(median_incomeE),\n    !is.na(total_popE),\n    total_popE > 0,\n    !is.na(over_65E)\n  )\n\nstate_median_tract_income <- median(criteria_tracts$median_incomeE, na.rm = TRUE)\nincome_threshold <- 0.8 * state_median_tract_income\nelderly_threshold <- 14\n\nvulnerable_tracts <- criteria_tracts %>%\n  filter(\n    median_incomeE <= income_threshold,\n    pct_over_65 >= elderly_threshold\n  )\n\nsummary_tbl <- criteria_tracts %>%\n  st_drop_geometry() %>%\n  summarize(\n    income_threshold = income_threshold,\n    elderly_threshold_pct = elderly_threshold,\n    n_total_tracts_used = n(),\n    n_vulnerable_tracts = sum(\n      median_incomeE <= income_threshold & pct_over_65 >= elderly_threshold,\n      na.rm = TRUE\n    ),\n    pct_vulnerable = n_vulnerable_tracts / n_total_tracts_used * 100\n  )\n\nknitr::kable(\n  summary_tbl,\n  digits = 2,\n  caption = \"Vulnerability thresholds and results (tracts with non-missing income and valid population only)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Vulnerability thresholds and results (tracts with non-missing income and valid population only)\n\n| income_threshold| elderly_threshold_pct| n_total_tracts_used| n_vulnerable_tracts| pct_vulnerable|\n|----------------:|---------------------:|-------------------:|-------------------:|--------------:|\n|          56150.4|                    14|                3383|                 525|          15.52|\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\n\nI define “low income” as census tracts with median household income at or below 80% of the statewide median tract income (ACS 2022). I chose the 80% cutoff because HUD commonly uses ≤80% of Area Median Income as a policy threshold for low-income eligibility in housing programs.\n\n- What elderly population threshold did you choose and why?\n\nI define “high-elderly” tracts as those with a 65+ population share ≥ 14%. This threshold follows WHO’s commonly cited typology, which describes a population as aged when more than 14% of residents are aged 65 and above. Some references also use 21% as the threshold for a super-aged society. For this statewide tract-level analysis, I adopt the 14% threshold to maintain a defensible standard while avoiding an overly restrictive definition.\n\n- How many tracts meet your vulnerability criteria? 525; 243 (When Threshold=21%)\t\n\n- What percentage of PA census tracts are considered vulnerable by your definition? 15.52%; 7.18%(When Threshold=21%)\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nvulnerable_tracts_proj <- vulnerable_tracts %>%\n  st_transform(5070)\nhospitals_proj <- hospitals %>%\n  st_transform(5070)\n\n# Calculate distance from each tract centroid to nearest hospital\nvulnerable_centroids <- st_centroid(vulnerable_tracts_proj)\ndistance_matrix <- st_distance(vulnerable_centroids, hospitals_proj)\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    nearest_hospital_distance = as.numeric(apply(distance_matrix, 1, min)),\n    nearest_hospital_miles = nearest_hospital_distance / 1609.344\n  )\n\ndistance_summary <- vulnerable_tracts_proj %>%\n  st_drop_geometry() %>%\n  summarize(\n    avg_distance = mean(nearest_hospital_miles, na.rm = TRUE),\n    max_distance = max(nearest_hospital_miles, na.rm = TRUE),\n    over_15_miles = sum(nearest_hospital_miles > 15, na.rm = TRUE)\n  )\n\nknitr::kable(\n  distance_summary,\n  digits = 2,\n  caption = \"Distance to nearest hospital for vulnerable tracts\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Distance to nearest hospital for vulnerable tracts\n\n| avg_distance| max_distance| over_15_miles|\n|------------:|------------:|-------------:|\n|         3.93|        25.65|            23|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania \n- Calculate distances in miles \t\n- Explain why you chose your projection \n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts? 4.59\n- What is the maximum distance? 25.65\n- How many vulnerable tracts are more than 15 miles from the nearest hospital? 13\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    underserved = nearest_hospital_miles > 15\n  )\n\nunderserved_summary <- vulnerable_tracts_proj %>%\n  st_drop_geometry() %>%\n  summarize(\n    n_vulnerable_tracts = n(),\n    n_underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = n_underserved / n_vulnerable_tracts * 100\n  )\nknitr::kable(\n  underserved_summary,\n  digits = 2,\n  caption = \"Underserved vulnerable tracts\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Underserved vulnerable tracts\n\n| n_vulnerable_tracts| n_underserved| pct_underserved|\n|-------------------:|-------------:|---------------:|\n|                 525|            23|            4.38|\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved? 13\n- What percentage of vulnerable tracts are underserved? 5.35%\n- Does this surprise you? Why or why not? \nI got 5.35%, which is somewhat surprising because I expected a higher share. This maybe suggests that most vulnerable tracts are actually within the service distance of hospitals.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties_proj <- pa_counties %>%\n  st_transform(st_crs(vulnerable_tracts_proj))\n\nvulnerable_with_county <- vulnerable_tracts_proj %>%\n  st_join(pa_counties_proj %>% select(COUNTY_NAM))\n\n# Aggregate statistics by county\ncounty_stats <- vulnerable_with_county %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarize(\n    n_vulnerable_tracts = n(),\n    n_underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = n_underserved_tracts / n_vulnerable_tracts * 100,\n    avg_distance_miles = mean(nearest_hospital_miles, na.rm = TRUE),\n    total_vulnerable_population = sum(total_popE, na.rm = TRUE),\n    vulnerable_pop_far_from_hospital = sum(if_else(underserved, total_popE, 0), na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n\nknitr::kable(\n  county_stats,\n  digits = 2,\n  caption = \"County-level statistics about vulnerable populations and hospital access\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: County-level statistics about vulnerable populations and hospital access\n\n|COUNTY_NAM     | n_vulnerable_tracts| n_underserved_tracts| pct_underserved| avg_distance_miles| total_vulnerable_population| vulnerable_pop_far_from_hospital|\n|:--------------|-------------------:|--------------------:|---------------:|------------------:|---------------------------:|--------------------------------:|\n|PERRY          |                   2|                    2|          100.00|              17.68|                        5800|                             5800|\n|MONROE         |                   3|                    2|           66.67|              12.84|                        7428|                             3222|\n|BRADFORD       |                   4|                    2|           50.00|              11.00|                       15457|                             8277|\n|CAMERON        |                   4|                    2|           50.00|              14.86|                        8919|                             4186|\n|FOREST         |                   4|                    2|           50.00|              15.20|                       10287|                             6959|\n|POTTER         |                   6|                    3|           50.00|              11.45|                       18242|                             7952|\n|SULLIVAN       |                   2|                    1|           50.00|              13.55|                        4828|                              918|\n|CLEARFIELD     |                  15|                    7|           46.67|              12.69|                       50192|                            19027|\n|CENTRE         |                   5|                    2|           40.00|              12.90|                       17464|                             5525|\n|TIOGA          |                   5|                    2|           40.00|              11.16|                       18027|                             5741|\n|ELK            |                   8|                    3|           37.50|              12.88|                       23115|                             9799|\n|CLARION        |                   6|                    2|           33.33|              11.71|                       16643|                             7237|\n|CLINTON        |                   3|                    1|           33.33|              10.97|                       10644|                             1948|\n|JUNIATA        |                   3|                    1|           33.33|              11.50|                        8494|                             1782|\n|JEFFERSON      |                  11|                    3|           27.27|               7.63|                       33987|                            10640|\n|COLUMBIA       |                   4|                    1|           25.00|               5.06|                       15247|                              918|\n|HUNTINGDON     |                   4|                    1|           25.00|              12.74|                        9799|                             1782|\n|WAYNE          |                   5|                    1|           20.00|               6.53|                       13904|                             1923|\n|FRANKLIN       |                   6|                    1|           16.67|               4.17|                       23731|                             1782|\n|MIFFLIN        |                   6|                    1|           16.67|              10.13|                       15600|                             1782|\n|WARREN         |                  12|                    2|           16.67|               7.83|                       41881|                             6959|\n|LYCOMING       |                   7|                    1|           14.29|               6.60|                       22079|                              918|\n|ARMSTRONG      |                   8|                    1|           12.50|               8.09|                       20182|                             4536|\n|INDIANA        |                   8|                    1|           12.50|               8.76|                       23416|                             4536|\n|CRAWFORD       |                   9|                    1|           11.11|               6.86|                       27863|                             2536|\n|DAUPHIN        |                  10|                    1|           10.00|               4.34|                       36061|                             4018|\n|VENANGO        |                  10|                    1|           10.00|               7.74|                       25575|                             2701|\n|ERIE           |                  13|                    1|            7.69|               4.26|                       46260|                             1320|\n|NORTHUMBERLAND |                  13|                    1|            7.69|              11.48|                       35368|                             4018|\n|LACKAWANNA     |                  19|                    1|            5.26|               2.80|                       50418|                             1923|\n|LUZERNE        |                  28|                    1|            3.57|               3.35|                       87167|                              918|\n|ADAMS          |                   1|                    0|            0.00|               0.19|                        3908|                                0|\n|ALLEGHENY      |                  85|                    0|            0.00|               2.31|                      212241|                                0|\n|BEAVER         |                  15|                    0|            0.00|               3.26|                       34409|                                0|\n|BEDFORD        |                   5|                    0|            0.00|               9.07|                       18774|                                0|\n|BERKS          |                   8|                    0|            0.00|               3.31|                       28223|                                0|\n|BLAIR          |                   7|                    0|            0.00|               2.58|                       17503|                                0|\n|BUCKS          |                   1|                    0|            0.00|               0.36|                        6247|                                0|\n|BUTLER         |                   4|                    0|            0.00|               3.82|                       14113|                                0|\n|CAMBRIA        |                  22|                    0|            0.00|               4.87|                       53658|                                0|\n|CARBON         |                   4|                    0|            0.00|               4.27|                       14033|                                0|\n|CHESTER        |                   1|                    0|            0.00|               7.40|                        2725|                                0|\n|CUMBERLAND     |                   4|                    0|            0.00|               1.10|                       15665|                                0|\n|DELAWARE       |                  13|                    0|            0.00|               1.42|                       43780|                                0|\n|FAYETTE        |                  26|                    0|            0.00|               6.02|                       84364|                                0|\n|FULTON         |                   2|                    0|            0.00|              12.33|                        5960|                                0|\n|GREENE         |                   4|                    0|            0.00|              10.56|                       17130|                                0|\n|LANCASTER      |                   3|                    0|            0.00|               4.44|                       11711|                                0|\n|LAWRENCE       |                  11|                    0|            0.00|               2.73|                       29115|                                0|\n|LEBANON        |                   3|                    0|            0.00|               3.96|                       11289|                                0|\n|LEHIGH         |                  12|                    0|            0.00|               2.65|                       49252|                                0|\n|MCKEAN         |                   6|                    0|            0.00|               8.48|                       13869|                                0|\n|MERCER         |                  10|                    0|            0.00|               1.56|                       28522|                                0|\n|MONTGOMERY     |                  11|                    0|            0.00|               1.57|                       44638|                                0|\n|NORTHAMPTON    |                  11|                    0|            0.00|               3.35|                       44621|                                0|\n|PHILADELPHIA   |                  73|                    0|            0.00|               1.10|                      296337|                                0|\n|SCHUYLKILL     |                  10|                    0|            0.00|               3.87|                       34401|                                0|\n|SNYDER         |                   1|                    0|            0.00|               9.35|                        2972|                                0|\n|SOMERSET       |                  11|                    0|            0.00|               6.46|                       38515|                                0|\n|SUSQUEHANNA    |                   2|                    0|            0.00|               3.64|                        5067|                                0|\n|UNION          |                   3|                    0|            0.00|               2.90|                       12057|                                0|\n|WASHINGTON     |                  17|                    0|            0.00|               4.83|                       44272|                                0|\n|WESTMORELAND   |                  34|                    0|            0.00|               3.62|                       88223|                                0|\n|YORK           |                  11|                    0|            0.00|               1.45|                       30167|                                0|\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts? \nCOLUMBIA, MONROE, PERRY, SULLIVAN,(100%); BRADFORD, CAMERON, CLINTON, DAUPHIN(50%)\n- Which counties have the most vulnerable people living far from hospitals? CLEARFIELD\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_stats %>%\n  arrange(desc(vulnerable_pop_far_from_hospital))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 64 × 7\n   COUNTY_NAM n_vulnerable_tracts n_underserved_tracts pct_underserved\n   <chr>                    <int>                <int>           <dbl>\n 1 CLEARFIELD                  15                    7            46.7\n 2 JEFFERSON                   11                    3            27.3\n 3 ELK                          8                    3            37.5\n 4 BRADFORD                     4                    2            50  \n 5 POTTER                       6                    3            50  \n 6 CLARION                      6                    2            33.3\n 7 FOREST                       4                    2            50  \n 8 WARREN                      12                    2            16.7\n 9 PERRY                        2                    2           100  \n10 TIOGA                        5                    2            40  \n# ℹ 54 more rows\n# ℹ 3 more variables: avg_distance_miles <dbl>,\n#   total_vulnerable_population <dbl>, vulnerable_pop_far_from_hospital <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_stats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 7\n  COUNTY_NAM n_vulnerable_tracts n_underserved_tracts pct_underserved\n  <chr>                    <int>                <int>           <dbl>\n1 PERRY                        2                    2           100  \n2 MONROE                       3                    2            66.7\n3 BRADFORD                     4                    2            50  \n4 CAMERON                      4                    2            50  \n5 FOREST                       4                    2            50  \n6 POTTER                       6                    3            50  \n# ℹ 3 more variables: avg_distance_miles <dbl>,\n#   total_vulnerable_population <dbl>, vulnerable_pop_far_from_hospital <dbl>\n```\n\n\n:::\n:::\n\n- Are there any patterns in where underserved counties are located?\nYes, the distribution of underserved counties shows a strong spatial pattern and continuity. They are concentrated in central and northern Pennsylvania, while there are relatively few in the southeastern and southwestern parts of the state. This may indicate that limited healthcare access is more likely to occur in inland counties with lower population density and a more sparse distribution of hospitals.\n\n::: {.cell}\n\n```{.r .cell-code}\ncounties_with_stats <- pa_counties_proj %>%\n  left_join(county_stats, by = \"COUNTY_NAM\")\nggplot(counties_with_stats) +\n  geom_sf(aes(fill = pct_underserved), color = \"white\", size = 0.2) +\n  scale_fill_viridis_c(\n    name = \"% Underserved\",\n    option = \"inferno\",\n    na.value = \"gray\"\n  ) +\n  labs(\n    title = \"Percent of Underserved Vulnerable Tracts by County\",\n    subtitle = \"Gray counties have no vulnerable tract data\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\npriority_counties <- county_stats %>%\n  arrange(\n    desc(vulnerable_pop_far_from_hospital),\n    desc(pct_underserved),\n    desc(avg_distance_miles)\n  ) %>%\n  select(\n    COUNTY_NAM,\n    n_vulnerable_tracts,\n    n_underserved_tracts,\n    pct_underserved,\n    avg_distance_miles,\n    total_vulnerable_population,\n    vulnerable_pop_far_from_hospital\n  ) %>%\n  head(10) %>%\n  rename(\n    County = COUNTY_NAM,\n    `Vulnerable Tracts` = n_vulnerable_tracts,\n    `Underserved Tracts` = n_underserved_tracts,\n    `Underserved Percentage` = pct_underserved,\n    `Avg Distance (miles)` = avg_distance_miles,\n    `Total Vulnerable Population` = total_vulnerable_population,\n    `Vulnerable Population Far from Hospital` = vulnerable_pop_far_from_hospital\n  ) %>%\n  mutate(\n    `Underserved Percentage` = sprintf(\"%.1f%%\", `Underserved Percentage`),\n    `Avg Distance (miles)` = sprintf(\"%.2f\", `Avg Distance (miles)`),\n    `Total Vulnerable Population` = scales::comma(`Total Vulnerable Population`),\n    `Vulnerable Population Far from Hospital` = scales::comma(`Vulnerable Population Far from Hospital`)\n  )\n\nknitr::kable(\n  priority_counties,\n  caption = \"Top 10 priority counties for healthcare investment (ranked by vulnerable population living far from hospital)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 priority counties for healthcare investment (ranked by vulnerable population living far from hospital)\n\n|County     | Vulnerable Tracts| Underserved Tracts|Underserved Percentage |Avg Distance (miles) |Total Vulnerable Population |Vulnerable Population Far from Hospital |\n|:----------|-----------------:|------------------:|:----------------------|:--------------------|:---------------------------|:---------------------------------------|\n|CLEARFIELD |                15|                  7|46.7%                  |12.69                |50,192                      |19,027                                  |\n|JEFFERSON  |                11|                  3|27.3%                  |7.63                 |33,987                      |10,640                                  |\n|ELK        |                 8|                  3|37.5%                  |12.88                |23,115                      |9,799                                   |\n|BRADFORD   |                 4|                  2|50.0%                  |11.00                |15,457                      |8,277                                   |\n|POTTER     |                 6|                  3|50.0%                  |11.45                |18,242                      |7,952                                   |\n|CLARION    |                 6|                  2|33.3%                  |11.71                |16,643                      |7,237                                   |\n|FOREST     |                 4|                  2|50.0%                  |15.20                |10,287                      |6,959                                   |\n|WARREN     |                12|                  2|16.7%                  |7.83                 |41,881                      |6,959                                   |\n|PERRY      |                 2|                  2|100.0%                 |17.68                |5,800                       |5,800                                   |\n|TIOGA      |                 5|                  2|40.0%                  |11.16                |18,027                      |5,741                                   |\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\ncounties_with_stats <- pa_counties_proj %>%\n  left_join(county_stats, by = \"COUNTY_NAM\")\n\ncounties_with_stats <- pa_counties_proj %>%\n  left_join(county_stats, by = \"COUNTY_NAM\")\n\nggplot(counties_with_stats) +\n  geom_sf(aes(fill = pct_underserved), color = \"white\", size = 0.2) +\n  geom_sf(data = hospitals, color = \"deepskyblue\", size = 0.6, alpha = 0.8) +\n  scale_fill_viridis_c(\n    name = \"% Underserved\",\n    option = \"magma\",\n    na.value = \"gray80\",\n    limits = c(0, 100),\n    labels = function(x) paste0(x, \"%\")\n  ) +\n  labs(\n    title = \"Percent of Underserved Vulnerable Tracts by County\",\n    subtitle = \"Hospital locations are shown as points; Gray counties have no vulnerable tract data\",\n    caption = \"Sources: Pennsylvania county boundaries and hospital locations; ACS 2022 tract data via tidycensus\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\npa_counties_map2 <- pa_counties %>%\n  st_transform(st_crs(vulnerable_tracts_proj))\n\nhospitals_map2 <- hospitals %>%\n  st_transform(st_crs(vulnerable_tracts_proj))\n\nggplot() +\n  geom_sf(\n    data = vulnerable_tracts_proj,\n    fill = \"deepskyblue4\",\n    color = \"white\",\n    size = 0.02,\n    alpha = 0.45\n  ) +\n  geom_sf(\n    data = vulnerable_tracts_proj %>%\n      filter(underserved),\n    fill = \"red\",\n    color = \"white\",\n    size = 0.05,\n    alpha = 0.85\n  ) +\n  geom_sf(\n    data = pa_counties_map2,\n    fill = NA,\n    color = \"gray\",\n    size = 0.25\n  ) +\n  geom_sf(\n    data = hospitals_map2,\n    color = \"orange\",\n    size = 0.5,\n    alpha = 0.9\n  ) +\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Red tracts are underserved vulnerable tracts; blue tracts are other vulnerable tracts; points are hospitals\",\n    caption = \"Sources: Pennsylvania county boundaries and hospitals; ACS 2022 tract demographics via tidycensus\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\ndistance_chart <- vulnerable_tracts_proj %>%\n  st_drop_geometry()\n\nggplot(distance_chart, aes(x = nearest_hospital_miles)) +\n  geom_histogram(\n    binwidth = 2,\n    fill = \"lightblue\",\n    color = \"white\"\n  ) +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital for Vulnerable Populations\",\n    subtitle = \"Pennsylvania vulnerable census tracts\",\n    x = \"Distance to nearest hospital (miles)\",\n    y = \"Number of vulnerable tracts\",\n    caption = \"Source: ACS 2022 and lecture hospital dataset\"\n)\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\nThe distribution is concentrated at shorter distances, with most vulnerable census tracts located within 0–5 miles of the nearest hospital. Only a small number of tracts are located more than 20 miles away.\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nparks <- st_read(\"C:/Users/cheny/Desktop/CPLN 5920 Public Policy Analytics/cpln-5920-sp26-student-portfolio-template/data/PPR_Properties/PPR_Properties.shp\", quiet = TRUE)\ncensus_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", cb = TRUE)\n\nnrow(parks)\nnrow(census_tracts)\n\nst_crs(parks)\nst_crs(census_tracts)\n\nparks <- st_transform(parks, 2272)\ncensus_tracts <- st_transform(census_tracts, 2272)\n\nst_crs(parks)\nst_crs(census_tracts)\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why? \n\nI selected three spatial datasets. I used PPR Properties as the parks layer, and Census tracts as the study area and the base unit for the later analysis. This combination fits my Green Space Equity topic because I need park locations, and tract boundaries to compare conditions across different areas.\n\n- What is the data source and date?\n\nThe data sources are OpenDataPhilly and the U.S. Census, with Census tract boundaries obtained through the tigris package in R. I downloaded the shapefiles for PPR Properties from OpenDataPhilly. The PPR Properties dataset was last updated on April 8, 2025. The Census tract boundaries were downloaded directly in R, and the data year is 2024.\n\n- How many features does it contain?\n\nPPR Properties (Parks): 504\n\nCensus tracts: 408\n\n- What CRS is it in? Did you need to transform it?\n\nBefore transformation, the three datasets were in different coordinate reference systems. PPR Properties was in WGS 84 / Pseudo-Mercator (EPSG:3857), while Census tracts were in NAD83 (EPSG:4269). \nBecause the layers did not share the same CRS, I transformed all three datasets to EPSG:2272 (NAD83 / Pennsylvania South, ftUS) so they use one common projected coordinate system for the later buffer and spatial analysis.\n\n---\n\n2. **Pose a research question**\n\nDo low-income and minority census tracts in Philadelphia have equitable access to green space?\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n# Get ACS tract demographic data\nacs_data <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2023,\n  survey = \"acs5\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    med_hh_income = \"B19013_001\",\n    race_total = \"B03002_001\",\n    white_nonhisp = \"B03002_003\"\n  ),\n  output = \"wide\",\n  geometry = FALSE\n)\n# Keep the main estimate columns and rename them\nacs_data_clean <- acs_data %>%\n  transmute(\n    GEOID,\n    total_pop = total_popE,\n    med_hh_income = med_hh_incomeE,\n    race_total = race_totalE,\n    white_nonhisp = white_nonhispE\n  )\n# Join ACS attributes to tract geometry\ntracts_analysis <- census_tracts %>%\n  left_join(acs_data_clean, by = \"GEOID\") %>%\n  mutate(\n    pct_nonwhite = if_else(\n      !is.na(race_total) & race_total > 0,\n      100 * (race_total - white_nonhisp) / race_total,\n      NA_real_\n    )\n  )\n# Check\nnrow(tracts_analysis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 408\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(tracts_analysis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"STATEFP\"       \"COUNTYFP\"      \"TRACTCE\"       \"GEOIDFQ\"      \n [5] \"GEOID\"         \"NAME\"          \"NAMELSAD\"      \"STUSPS\"       \n [9] \"NAMELSADCO\"    \"STATE_NAME\"    \"LSAD\"          \"ALAND\"        \n[13] \"AWATER\"        \"total_pop\"     \"med_hh_income\" \"race_total\"   \n[17] \"white_nonhisp\" \"geometry\"      \"pct_nonwhite\" \n```\n\n\n:::\n\n```{.r .cell-code}\n# Fix invalid geometries (By GPT)\nparks_poly <- parks[st_geometry_type(parks) %in% c(\"POLYGON\", \"MULTIPOLYGON\"), ]\nparks_poly <- st_make_valid(parks_poly)\ntracts_analysis <- st_make_valid(tracts_analysis)\nparks_poly <- st_collection_extract(parks_poly, \"POLYGON\")\ntracts_analysis <- st_collection_extract(tracts_analysis, \"POLYGON\")\nparks_poly <- parks_poly[!st_is_empty(parks_poly), ]\ntracts_analysis <- tracts_analysis[!st_is_empty(tracts_analysis), ]\nparks_poly <- st_set_precision(parks_poly, 1)\ntracts_analysis <- st_set_precision(tracts_analysis, 1)\nparks_poly <- st_buffer(parks_poly, 0)\ntracts_analysis <- st_buffer(tracts_analysis, 0)\nsum(!st_is_valid(parks_poly))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(!st_is_valid(tracts_analysis))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\ntracts_union <- st_union(tracts_analysis)\n# Clip parks to city boundary first\nparks_poly_clip <- st_intersection(parks_poly, tracts_union)\n# Then intersect clipped parks with tracts\npark_in_tract <- st_intersection(\n  parks_poly_clip,\n  tracts_analysis %>% select(GEOID)\n)\n\n# Create 0.5-mile buffers around parks\nbuffer_dist_ft <- 2640\npark_buffers <- st_buffer(parks, dist = buffer_dist_ft)\n# Dissolve overlapping buffers\npark_buffer_union <- st_union(park_buffers)\n# Intersect tract polygons with the park buffers\ntract_buffer_cover <- st_intersection(\n  tracts_analysis %>% select(GEOID),\n  park_buffer_union\n)\n# Calculate covered area within each tract\nbuffer_cover_by_tract <- tract_buffer_cover %>%\n  mutate(buffer_cover_acres = as.numeric(st_area(geometry)) / 43560) %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(buffer_cover_acres = sum(buffer_cover_acres, na.rm = TRUE), .groups = \"drop\")\n# Calculate total tract area\ntracts_analysis <- tracts_analysis %>%\n  mutate(tract_acres = as.numeric(st_area(geometry)) / 43560)\n# Calculate park access percent\ntracts_analysis <- tracts_analysis %>%\n  left_join(buffer_cover_by_tract, by = \"GEOID\") %>%\n  mutate(\n    buffer_cover_acres = dplyr::coalesce(buffer_cover_acres, 0),\n    park_access_pct = if_else(tract_acres > 0, 100 * buffer_cover_acres / tract_acres, NA_real_)\n  )\n\n# Tract-level park 10-minute access table\npark_access_table <- tracts_analysis %>%\n  st_drop_geometry() %>%\n  select(GEOID, NAME, med_hh_income, pct_nonwhite, park_access_pct) %>%\n  mutate(\n    med_hh_income = round(med_hh_income, 0),\n    pct_nonwhite = round(pct_nonwhite, 1),\n    park_access_pct = round(park_access_pct, 1)\n  ) %>%\n  arrange(park_access_pct)\n\npark_access_table %>%\n  knitr::kable(\n    caption = \"Park Walking Access Census Tracts in Philadelphia (10-minute walk park buffer)\",\n    col.names = c(\"GEOID\", \"Tract\", \"Median HH Income\", \"% Non-White\", \"Park Access %\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Park Walking Access Census Tracts in Philadelphia (10-minute walk park buffer)\n\n|GEOID       |Tract   | Median HH Income| % Non-White| Park Access %|\n|:-----------|:-------|----------------:|-----------:|-------------:|\n|42101008801 |88.01   |            33990|        46.2|           1.3|\n|42101005400 |54      |            56197|        85.5|          11.1|\n|42101980701 |9807.01 |               NA|          NA|          11.2|\n|42101989200 |9892    |               NA|          NA|          24.1|\n|42101980400 |9804    |               NA|          NA|          24.7|\n|42101980702 |9807.02 |               NA|          NA|          29.8|\n|42101036000 |360     |            63170|        49.9|          30.1|\n|42101980901 |9809.01 |               NA|          NA|          30.8|\n|42101026301 |263.01  |            67379|        97.8|          34.5|\n|42101026900 |269     |            69769|        81.0|          34.6|\n|42101035702 |357.02  |            64919|        30.5|          37.1|\n|42101980906 |9809.06 |               NA|          NA|          42.4|\n|42101036501 |365.01  |            83697|        24.3|          45.4|\n|42101030700 |307     |            58623|        78.5|          54.3|\n|42101026800 |268     |            41330|        86.8|          56.7|\n|42101980905 |9809.05 |               NA|          NA|          57.7|\n|42101036400 |364     |           101094|        20.1|          58.4|\n|42101037800 |378     |            63772|        21.2|          58.9|\n|42101026000 |260     |            64868|        98.6|          60.0|\n|42101035800 |358     |            63375|        33.3|          61.6|\n|42101034600 |346     |            63115|        64.5|          64.5|\n|42101030600 |306     |            44108|        63.6|          65.0|\n|42101031401 |314.01  |            56818|        62.2|          68.2|\n|42101989300 |9893    |               NA|        78.8|          68.6|\n|42101036902 |369.02  |            31635|        47.3|          69.1|\n|42101026600 |266     |            52267|        97.7|          69.4|\n|42101026100 |261     |            56546|        95.7|          69.8|\n|42101018300 |183     |            77011|        11.0|          72.8|\n|42101035602 |356.02  |           106480|        45.0|          73.1|\n|42101980300 |9803    |               NA|          NA|          73.2|\n|42101011700 |117     |           127083|        55.7|          73.5|\n|42101005600 |56      |            35474|        95.7|          73.7|\n|42101034502 |345.02  |            66557|        55.7|          74.0|\n|42101037900 |379     |            81528|         8.9|          74.2|\n|42101033500 |335     |            47289|        66.2|          74.3|\n|42101033600 |336     |            46191|        55.7|          75.2|\n|42101038000 |380     |            57386|        51.9|          77.9|\n|42101008802 |88.02   |            31293|        56.0|          80.2|\n|42101038700 |387     |           124792|        22.8|          81.7|\n|42101026302 |263.02  |            77160|        98.3|          82.1|\n|42101035500 |355     |            69439|        32.6|          84.6|\n|42101012100 |121     |            53377|        80.4|          87.2|\n|42101038301 |383.01  |            32337|        91.7|          88.6|\n|42101035900 |359     |            48571|        31.8|          88.8|\n|42101039001 |390.01  |            41296|        96.9|          89.2|\n|42101033800 |338     |            67683|        36.7|          90.7|\n|42101037500 |375     |            78387|        55.9|          91.1|\n|42101031000 |310     |            68652|        74.2|          92.3|\n|42101036301 |363.01  |            82596|        44.2|          93.8|\n|42101036100 |361     |           105208|        32.6|          94.0|\n|42101025500 |255     |            78798|        47.9|          95.2|\n|42101009000 |90      |            38976|        45.7|          95.6|\n|42101036600 |366     |           168021|        33.8|          95.9|\n|42101025800 |258     |            50813|        94.5|          96.0|\n|42101012204 |122.04  |            46037|        85.7|          96.3|\n|42101031402 |314.02  |            61318|        88.6|          96.7|\n|42101028901 |289.01  |            39087|        94.9|          96.9|\n|42101027000 |270     |            95619|        87.0|          97.0|\n|42101980600 |9806    |               NA|          NA|          97.5|\n|42101980904 |9809.04 |               NA|          NA|          97.6|\n|42101029100 |291     |            26290|        98.3|          97.7|\n|42101021600 |216     |           101075|        28.2|          97.8|\n|42101038200 |382     |            44164|        44.5|          98.0|\n|42101009100 |91      |            35139|        64.7|          98.1|\n|42101035601 |356.01  |            61939|        34.1|          98.3|\n|42101030800 |308     |            59281|        72.3|          98.5|\n|42101030900 |309     |            56782|        81.8|          98.6|\n|42101039002 |390.02  |            64733|        93.4|          98.8|\n|42101028700 |287     |            26707|        98.0|          98.9|\n|42101031800 |318     |            65556|        78.8|          98.9|\n|42101026700 |267     |            51021|        99.9|          99.6|\n|42101036901 |369.01  |               NA|       100.0|          99.7|\n|42101022000 |220     |            94750|        25.5|          99.9|\n|42101031200 |312     |            52211|        90.8|          99.9|\n|42101001700 |17      |           145833|        34.7|         100.0|\n|42101002500 |25      |            83508|        37.5|         100.0|\n|42101006100 |61      |            45521|        93.2|         100.0|\n|42101007700 |77      |            60817|        42.8|         100.0|\n|42101009200 |92      |            54271|        76.8|         100.0|\n|42101011300 |113     |            44545|        98.7|         100.0|\n|42101011500 |115     |            87349|        92.2|         100.0|\n|42101013200 |132     |            44299|        73.2|         100.0|\n|42101014000 |140     |            49234|        62.4|         100.0|\n|42101016500 |165     |               NA|        97.5|         100.0|\n|42101019700 |197     |            32063|        98.0|         100.0|\n|42101027901 |279.01  |            36135|        99.9|         100.0|\n|42101029400 |294     |            33661|        90.5|         100.0|\n|42101032500 |325     |            52342|        53.9|         100.0|\n|42101034802 |348.02  |            56032|        40.1|         100.0|\n|42101017602 |176.02  |            32523|        97.2|         100.0|\n|42101980500 |9805    |               NA|          NA|         100.0|\n|42101010300 |103     |            32045|        98.9|         100.0|\n|42101000500 |5       |            68977|        66.3|         100.0|\n|42101014800 |148     |               NA|        97.0|         100.0|\n|42101001204 |12.04   |            94056|        17.6|         100.0|\n|42101000101 |1.01    |           108438|        16.4|         100.0|\n|42101980903 |9809.03 |               NA|          NA|         100.0|\n|42101000600 |6       |           145036|        33.6|         100.0|\n|42101001500 |15      |           108378|        27.5|         100.0|\n|42101002100 |21      |           116354|        53.1|         100.0|\n|42101002900 |29      |           104981|        29.5|         100.0|\n|42101003600 |36      |            43688|        87.0|         100.0|\n|42101004101 |41.01   |            72500|        71.3|         100.0|\n|42101004201 |42.01   |            84500|        40.9|         100.0|\n|42101006200 |62      |            48634|        96.8|         100.0|\n|42101006600 |66      |            27206|        94.7|         100.0|\n|42101007300 |73      |            71106|        77.6|         100.0|\n|42101008301 |83.01   |            35174|        96.2|         100.0|\n|42101009300 |93      |            40933|        96.3|         100.0|\n|42101010100 |101     |            46492|        97.7|         100.0|\n|42101016300 |163     |            39872|        91.2|         100.0|\n|42101016901 |169.01  |            38958|        98.9|         100.0|\n|42101017500 |175     |            30823|        97.3|         100.0|\n|42101018001 |180.01  |            59221|        15.9|         100.0|\n|42101019502 |195.02  |            28291|       100.0|         100.0|\n|42101019900 |199     |            28803|        99.4|         100.0|\n|42101020200 |202     |            35000|        98.4|         100.0|\n|42101021300 |213     |            98196|        12.2|         100.0|\n|42101021800 |218     |            70354|        43.7|         100.0|\n|42101024300 |243     |            56364|        79.5|         100.0|\n|42101024800 |248     |            50385|        98.2|         100.0|\n|42101026200 |262     |            59954|        98.6|         100.0|\n|42101027401 |274.01  |            49869|        96.3|         100.0|\n|42101030100 |301     |               NA|        89.9|         100.0|\n|42101031300 |313     |            63241|        84.2|         100.0|\n|42101032600 |326     |            80283|        50.1|         100.0|\n|42101008302 |83.02   |            29571|        97.3|         100.0|\n|42101037600 |376     |           101742|        45.6|         100.0|\n|42101034501 |345.01  |            47142|        45.8|         100.0|\n|42101002000 |20      |           106420|        60.2|         100.0|\n|42101015600 |156     |            64125|        70.0|         100.0|\n|42101000701 |7.01    |            90343|        23.0|         100.0|\n|42101980003 |9800.03 |               NA|          NA|         100.0|\n|42101000102 |1.02    |           108203|        14.7|         100.0|\n|42101020701 |207.01  |           115402|        23.7|         100.0|\n|42101980902 |9809.02 |               NA|          NA|         100.0|\n|42101036700 |367     |           156638|        31.8|         100.0|\n|42101014500 |145     |            42619|        87.9|         100.0|\n|42101001800 |18      |           121719|        27.7|         100.0|\n|42101003002 |30.02   |            78843|        55.8|         100.0|\n|42101006700 |67      |            43220|        98.1|         100.0|\n|42101011200 |112     |            28958|        99.7|         100.0|\n|42101013401 |134.01  |           147361|        15.4|         100.0|\n|42101017701 |177.01  |            37917|        94.8|         100.0|\n|42101021100 |211     |            92610|        26.2|         100.0|\n|42101031102 |311.02  |            62411|        96.0|         100.0|\n|42101033900 |339     |            58660|        47.1|         100.0|\n|42101010400 |104     |            31063|        95.9|         100.0|\n|42101010600 |106     |            19013|        93.0|         100.0|\n|42101008000 |80      |            70526|        78.0|         100.0|\n|42101010000 |100     |            54871|        94.9|         100.0|\n|42101015101 |151.01  |            48019|        90.9|         100.0|\n|42101038500 |385     |           124324|        16.2|         100.0|\n|42101026400 |264     |            63867|        99.6|         100.0|\n|42101004103 |41.03   |            52083|        80.6|         100.0|\n|42101016200 |162     |            39009|        88.6|         100.0|\n|42101000902 |9.02    |            85271|        31.8|         100.0|\n|42101006400 |64      |            42469|        95.0|         100.0|\n|42101024400 |244     |            53333|        89.7|         100.0|\n|42101027100 |271     |            60255|        95.3|         100.0|\n|42101034100 |341     |            72275|        29.7|         100.0|\n|42101016001 |160.01  |           111170|         4.5|         100.0|\n|42101001101 |11.01   |            61850|        40.4|         100.0|\n|42101007800 |78      |            63348|        43.7|         100.0|\n|42101019501 |195.01  |            25590|        97.9|         100.0|\n|42101025400 |254     |            68287|        85.8|         100.0|\n|42101031501 |315.01  |            59738|        60.0|         100.0|\n|42101013300 |133     |            98373|        52.5|         100.0|\n|42101024000 |240     |            63795|        71.9|         100.0|\n|42101020702 |207.02  |           192727|        30.2|         100.0|\n|42101000200 |2       |            97256|        55.4|         100.0|\n|42101001201 |12.01   |           119683|        19.2|         100.0|\n|42101004002 |40.02   |            94150|        27.3|         100.0|\n|42101010700 |107     |            42569|        92.3|         100.0|\n|42101017800 |178     |            42104|        82.2|         100.0|\n|42101021900 |219     |            78542|        19.2|         100.0|\n|42101008101 |81.01   |            47614|        88.7|         100.0|\n|42101033300 |333     |            55389|        43.1|         100.0|\n|42101007101 |71.01   |            44286|        94.0|         100.0|\n|42101000806 |8.06    |           179609|        24.3|         100.0|\n|42101037200 |372     |            75185|        49.1|         100.0|\n|42101014700 |147     |            26018|        67.4|         100.0|\n|42101015800 |158     |           116629|        21.6|         100.0|\n|42101020300 |203     |            49115|        97.5|         100.0|\n|42101027300 |273     |            42423|        89.6|         100.0|\n|42101028300 |283     |            37300|        96.8|         100.0|\n|42101030200 |302     |            60625|        80.3|         100.0|\n|42101031502 |315.02  |            45282|        58.4|         100.0|\n|42101001102 |11.02   |           136310|        26.8|         100.0|\n|42101002400 |24      |            84732|        25.7|         100.0|\n|42101002802 |28.02   |            94427|        41.0|         100.0|\n|42101003200 |32      |            68250|        75.9|         100.0|\n|42101036303 |363.03  |           100857|        19.3|         100.0|\n|42101007000 |70      |            41206|        98.8|         100.0|\n|42101007400 |74      |            36250|        88.8|         100.0|\n|42101017601 |176.01  |            27006|        95.5|         100.0|\n|42101008602 |86.02   |            32127|        69.0|         100.0|\n|42101009400 |94      |            30335|        99.4|         100.0|\n|42101009801 |98.01   |            75446|        94.0|         100.0|\n|42101010200 |102     |            23750|        99.1|         100.0|\n|42101010900 |109     |            31343|        81.4|         100.0|\n|42101011100 |111     |            47632|        98.8|         100.0|\n|42101011400 |114     |            44416|        95.2|         100.0|\n|42101012000 |120     |            61483|        72.2|         100.0|\n|42101013100 |131     |            31924|        69.3|         100.0|\n|42101013402 |134.02  |            92500|        20.6|         100.0|\n|42101013602 |136.02  |           131705|        19.3|         100.0|\n|42101037700 |377     |            22621|        65.1|         100.0|\n|42101016400 |164     |            24497|        98.0|         100.0|\n|42101016902 |169.02  |            22422|       100.0|         100.0|\n|42101017100 |171     |            27300|        94.7|         100.0|\n|42101019200 |192     |            13721|        90.3|         100.0|\n|42101020101 |201.01  |            28559|        98.3|         100.0|\n|42101020900 |209     |           125064|        27.4|         100.0|\n|42101021700 |217     |            86222|        27.5|         100.0|\n|42101023700 |237     |            68676|        72.2|         100.0|\n|42101024900 |249     |            24904|        99.0|         100.0|\n|42101025300 |253     |            55988|        88.8|         100.0|\n|42101026500 |265     |            46806|        95.9|         100.0|\n|42101027402 |274.02  |            71551|        92.8|         100.0|\n|42101028400 |284     |            28236|        93.3|         100.0|\n|42101028800 |288     |            57996|        94.0|         100.0|\n|42101030502 |305.02  |            50245|        91.5|         100.0|\n|42101030501 |305.01  |            50240|        94.7|         100.0|\n|42101032300 |323     |            40300|        72.2|         100.0|\n|42101033101 |331.01  |            60333|        55.7|         100.0|\n|42101033701 |337.01  |            48682|        58.4|         100.0|\n|42101034400 |344     |           118397|        28.9|         100.0|\n|42101034701 |347.01  |            77800|        46.6|         100.0|\n|42101034900 |349     |            54689|        66.2|         100.0|\n|42101035200 |352     |            88663|        14.9|         100.0|\n|42101036203 |362.03  |            85733|        17.7|         100.0|\n|42101001002 |10.02   |           137250|        14.9|         100.0|\n|42101001001 |10.01   |           114205|        10.3|         100.0|\n|42101000803 |8.03    |            86538|        19.0|         100.0|\n|42101980200 |9802    |               NA|        42.7|         100.0|\n|42101012203 |122.03  |            63409|        73.8|         100.0|\n|42101009500 |95      |            32935|        99.0|         100.0|\n|42101010500 |105     |            38581|        94.6|         100.0|\n|42101024100 |241     |            18646|        80.3|         100.0|\n|42101013601 |136.01  |           108867|        21.3|         100.0|\n|42101038100 |381     |            39939|        55.4|         100.0|\n|42101004104 |41.04   |            62857|        62.2|         100.0|\n|42101013702 |137.02  |            82660|        56.5|         100.0|\n|42101001203 |12.03   |           107537|        20.0|         100.0|\n|42101039100 |391     |            24963|       100.0|         100.0|\n|42101000901 |9.01    |            51384|        46.5|         100.0|\n|42101001400 |14      |            98981|        34.3|         100.0|\n|42101001900 |19      |           144261|        45.6|         100.0|\n|42101002200 |22      |            73462|        55.7|         100.0|\n|42101002701 |27.01   |            95224|        42.6|         100.0|\n|42101003001 |30.01   |            55288|        70.7|         100.0|\n|42101003100 |31      |            83620|        64.9|         100.0|\n|42101003300 |33      |            80850|        65.3|         100.0|\n|42101003702 |37.02   |            47760|        78.6|         100.0|\n|42101035301 |353.01  |            90970|        22.7|         100.0|\n|42101003901 |39.01   |            59262|        50.5|         100.0|\n|42101035701 |357.01  |            61399|        50.1|         100.0|\n|42101006000 |60      |            44199|        90.0|         100.0|\n|42101006300 |63      |            32997|        97.7|         100.0|\n|42101006500 |65      |            48173|        98.5|         100.0|\n|42101007102 |71.02   |            40602|        97.4|         100.0|\n|42101008102 |81.02   |            53289|        90.1|         100.0|\n|42101008200 |82      |            35518|        96.6|         100.0|\n|42101008500 |85      |            45747|        86.8|         100.0|\n|42101008701 |87.01   |            61621|        45.7|         100.0|\n|42101009600 |96      |            42297|       100.0|         100.0|\n|42101009802 |98.02   |            79531|        95.9|         100.0|\n|42101013500 |135     |           146792|        20.7|         100.0|\n|42101013900 |139     |            52741|        69.4|         100.0|\n|42101014900 |149     |            37431|        94.3|         100.0|\n|42101015200 |152     |            42256|        96.2|         100.0|\n|42101015700 |157     |            88125|        47.3|         100.0|\n|42101016100 |161     |           102324|        51.4|         100.0|\n|42101016600 |166     |            57778|        86.5|         100.0|\n|42101016800 |168     |            27100|        96.5|         100.0|\n|42101017000 |170     |            36677|        81.6|         100.0|\n|42101017202 |172.02  |            48229|        99.1|         100.0|\n|42101017900 |179     |            53343|        61.4|         100.0|\n|42101018002 |180.02  |            70579|        35.8|         100.0|\n|42101019100 |191     |            50238|        85.8|         100.0|\n|42101019800 |198     |            36502|        97.2|         100.0|\n|42101020102 |201.02  |            33947|        99.4|         100.0|\n|42101021000 |210     |            88924|        20.7|         100.0|\n|42101021200 |212     |           109861|        16.7|         100.0|\n|42101021500 |215     |           121667|        30.6|         100.0|\n|42101023800 |238     |            66691|        72.6|         100.0|\n|42101023900 |239     |            45294|        72.7|         100.0|\n|42101024500 |245     |            21117|        92.6|         100.0|\n|42101024700 |247     |            47849|        94.8|         100.0|\n|42101025700 |257     |            63542|        52.3|         100.0|\n|42101034801 |348.01  |            64608|        23.2|         100.0|\n|42101027500 |275     |            61875|        94.8|         100.0|\n|42101027700 |277     |               NA|        98.1|         100.0|\n|42101028000 |280     |            36463|        99.4|         100.0|\n|42101028100 |281     |            55313|        89.9|         100.0|\n|42101028200 |282     |            34420|        97.4|         100.0|\n|42101028902 |289.02  |            38775|        95.7|         100.0|\n|42101029200 |292     |            77816|        78.8|         100.0|\n|42101029800 |298     |            47292|        84.8|         100.0|\n|42101029900 |299     |            34487|        91.3|         100.0|\n|42101031101 |311.01  |            51460|        81.6|         100.0|\n|42101031700 |317     |            36880|        76.7|         100.0|\n|42101032000 |320     |            60957|        54.1|         100.0|\n|42101032100 |321     |            50409|        65.0|         100.0|\n|42101032900 |329     |            57571|        63.9|         100.0|\n|42101033400 |334     |            55102|        49.8|         100.0|\n|42101033702 |337.02  |            67557|        42.9|         100.0|\n|42101035302 |353.02  |            71232|        37.4|         100.0|\n|42101014100 |141     |            21211|        71.3|         100.0|\n|42101017400 |174     |            35528|        98.8|         100.0|\n|42101020600 |206     |            65580|        50.6|         100.0|\n|42101029300 |293     |            34076|        63.1|         100.0|\n|42101002702 |27.02   |            99797|        25.8|         100.0|\n|42101038600 |386     |           180000|        29.6|         100.0|\n|42101008601 |86.01   |            87875|        43.9|         100.0|\n|42101023100 |231     |           179911|        15.8|         100.0|\n|42101000404 |4.04    |            93998|        22.2|         100.0|\n|42101000805 |8.05    |            90741|        25.6|         100.0|\n|42101013701 |137.01  |            94396|        62.1|         100.0|\n|42101001301 |13.01   |           133320|        38.1|         100.0|\n|42101018801 |188.01  |            22349|        84.3|         100.0|\n|42101980001 |9800.01 |               NA|          NA|         100.0|\n|42101012502 |125.02  |           109602|        34.6|         100.0|\n|42101035100 |351     |            66523|        30.1|         100.0|\n|42101036502 |365.02  |            85750|        20.7|         100.0|\n|42101004202 |42.02   |            75984|        39.3|         100.0|\n|42101008702 |87.02   |            56181|        37.9|         100.0|\n|42101010800 |108     |            32999|        93.9|         100.0|\n|42101011900 |119     |            63628|        93.5|         100.0|\n|42101016702 |167.02  |            34063|        97.6|         100.0|\n|42101018400 |184     |            73478|         8.1|         100.0|\n|42101020000 |200     |            18510|        84.8|         100.0|\n|42101023600 |236     |           105491|        49.7|         100.0|\n|42101027600 |276     |            65282|        96.9|         100.0|\n|42101028600 |286     |            60892|        97.8|         100.0|\n|42101030000 |300     |            33419|        87.7|         100.0|\n|42101031900 |319     |            45846|        71.4|         100.0|\n|42101034803 |348.03  |            78224|        19.3|         100.0|\n|42101034702 |347.02  |            85298|        22.4|         100.0|\n|42101037300 |373     |           113636|        16.7|         100.0|\n|42101020800 |208     |            71701|        58.5|         100.0|\n|42101989100 |9891    |               NA|        90.8|         100.0|\n|42101001600 |16      |           144954|        12.4|         100.0|\n|42101012201 |122.01  |            42782|        79.4|         100.0|\n|42101016002 |160.02  |           110681|        22.9|         100.0|\n|42101000403 |4.03    |           187743|        25.6|         100.0|\n|42101014202 |142.02  |           101488|        31.8|         100.0|\n|42101008400 |84      |            53182|        97.3|         100.0|\n|42101014300 |143     |           127520|        18.9|         100.0|\n|42101024200 |242     |            46144|        76.4|         100.0|\n|42101038900 |389     |            66705|        92.1|         100.0|\n|42101027200 |272     |            64102|        97.6|         100.0|\n|42101027800 |278     |            33655|        98.6|         100.0|\n|42101002801 |28.01   |            71027|        51.5|         100.0|\n|42101036201 |362.01  |            93300|        15.8|         100.0|\n|42101005500 |55      |            67063|        93.8|         100.0|\n|42101014400 |144     |           129023|        41.2|         100.0|\n|42101017702 |177.02  |            29551|        93.4|         100.0|\n|42101020400 |204     |            46037|        97.9|         100.0|\n|42101038800 |388     |           113343|        38.4|         100.0|\n|42101014201 |142.01  |           149475|        20.0|         100.0|\n|42101011000 |110     |            29122|        90.7|         100.0|\n|42101015300 |153     |            30915|        62.3|         100.0|\n|42101017300 |173     |            26875|        95.2|         100.0|\n|42101020500 |205     |               NA|        97.3|         100.0|\n|42101029000 |290     |            40870|        95.4|         100.0|\n|42101031600 |316     |            42176|        67.4|         100.0|\n|42101980002 |9800.02 |               NA|          NA|         100.0|\n|42101001302 |13.02   |           101884|        21.4|         100.0|\n|42101033102 |331.02  |            61373|        39.2|         100.0|\n|42101003800 |38      |            94538|        13.5|         100.0|\n|42101980100 |9801    |           108889|         4.7|         100.0|\n|42101034200 |342     |            66692|        33.1|         100.0|\n|42101023500 |235     |            94904|        41.1|         100.0|\n|42101015102 |151.02  |            22720|        98.6|         100.0|\n|42101024600 |246     |            53414|        85.5|         100.0|\n|42101028500 |285     |               NA|        99.2|         100.0|\n|42101007900 |79      |            85018|        45.2|         100.0|\n|42101011800 |118     |            35515|        98.8|         100.0|\n|42101014600 |146     |            51563|        65.4|         100.0|\n|42101021400 |214     |            82297|        18.9|         100.0|\n|42101025600 |256     |            87788|        50.9|         100.0|\n|42101027902 |279.02  |            44509|        72.0|         100.0|\n|42101034000 |340     |           104488|        44.4|         100.0|\n|42101980800 |9808    |               NA|          NA|         100.0|\n|42101000401 |4.01    |            89663|        52.3|         100.0|\n|42101000300 |3       |           102330|        40.1|         100.0|\n|42101003902 |39.02   |            87258|        18.5|         100.0|\n|42101007200 |72      |            50660|        98.4|         100.0|\n|42101033000 |330     |            65749|        67.6|         100.0|\n|42101036202 |362.02  |            95026|        15.6|         100.0|\n|42101017201 |172.01  |            26313|        99.2|         100.0|\n|42101019000 |190     |            36857|        86.1|         100.0|\n|42101038400 |384     |           116250|        27.4|         100.0|\n|42101025200 |252     |            30596|        90.1|         100.0|\n|42101012501 |125.01  |            82700|        34.9|         100.0|\n|42101018802 |188.02  |            47529|        95.8|         100.0|\n|42101025900 |259     |            53713|        97.7|         100.0|\n|42101036302 |363.02  |            84528|        46.6|         100.0|\n|42101000702 |7.02    |            63200|        47.6|         100.0|\n|42101004001 |40.01   |            82258|        26.8|         100.0|\n|42101003701 |37.01   |            69896|        75.8|         100.0|\n|42101000801 |8.01    |           130096|        28.3|         100.0|\n|42101013800 |138     |            63523|        70.3|         100.0|\n|42101033200 |332     |            71691|        57.4|         100.0|\n|42101016701 |167.01  |            52656|        96.5|         100.0|\n|42101002300 |23      |           125781|        27.6|         100.0|\n\n\n:::\n\n```{.r .cell-code}\n# Intersect park polygons with census tracts\npark_in_tract <- st_intersection(\n  parks_poly,\n  tracts_analysis %>% select(GEOID)\n)\n# Calculate park area for each intersected piece\npark_area_by_tract <- park_in_tract %>%\n  mutate(park_acres = as.numeric(st_area(geometry)) / 43560) %>%\n  st_drop_geometry() %>%\n  group_by(GEOID) %>%\n  summarise(park_acres = sum(park_acres, na.rm = TRUE), .groups = \"drop\")\n# Join park area to tract data\ntracts_analysis <- tracts_analysis %>%\n  select(-any_of(c(\"park_acres\", \"park_acres_per_1000\"))) %>%\n  left_join(park_area_by_tract, by = \"GEOID\") %>%\n  mutate(\n    park_acres = dplyr::coalesce(park_acres, 0),\n    park_acres_per_1000 = if_else(\n      !is.na(total_pop) & total_pop > 0,\n      1000 * park_acres / total_pop,\n      NA_real_\n    )\n  )\n# Tract-level park acreage per 1,000 residents table\npark_acres_table <- tracts_analysis %>%\n  st_drop_geometry() %>%\n  select(GEOID, NAME, med_hh_income, pct_nonwhite, park_acres, park_acres_per_1000) %>%\n  mutate(\n    med_hh_income = round(med_hh_income, 0),\n    pct_nonwhite = round(pct_nonwhite, 1),\n    park_acres = round(park_acres, 2),\n    park_acres_per_1000 = round(park_acres_per_1000, 2)\n  ) %>%\n  arrange(park_acres_per_1000)\n\npark_acres_table %>%\n  knitr::kable(\n    caption = \"Park Acreage per 1,000 Residents by Census Tract in Philadelphia\",\n    col.names = c(\"GEOID\", \"Tract\", \"Median HH Income\", \"% Non-White\", \"Park Acres\", \"Park Acres per 1,000\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Park Acreage per 1,000 Residents by Census Tract in Philadelphia\n\n|GEOID       |Tract   | Median HH Income| % Non-White| Park Acres| Park Acres per 1,000|\n|:-----------|:-------|----------------:|-----------:|----------:|--------------------:|\n|42101011500 |115     |            87349|        92.2|       0.00|                 0.00|\n|42101018300 |183     |            77011|        11.0|       0.00|                 0.00|\n|42101019700 |197     |            32063|        98.0|       0.00|                 0.00|\n|42101026100 |261     |            56546|        95.7|       0.00|                 0.00|\n|42101029400 |294     |            33661|        90.5|       0.00|                 0.00|\n|42101031000 |310     |            68652|        74.2|       0.00|                 0.00|\n|42101034600 |346     |            63115|        64.5|       0.00|                 0.00|\n|42101000500 |5       |            68977|        66.3|       0.00|                 0.00|\n|42101001204 |12.04   |            94056|        17.6|       0.00|                 0.00|\n|42101000600 |6       |           145036|        33.6|       0.00|                 0.00|\n|42101006600 |66      |            27206|        94.7|       0.00|                 0.00|\n|42101007300 |73      |            71106|        77.6|       0.00|                 0.00|\n|42101009300 |93      |            40933|        96.3|       0.00|                 0.00|\n|42101010100 |101     |            46492|        97.7|       0.00|                 0.00|\n|42101021300 |213     |            98196|        12.2|       0.00|                 0.00|\n|42101026700 |267     |            51021|        99.9|       0.00|                 0.00|\n|42101027401 |274.01  |            49869|        96.3|       0.00|                 0.00|\n|42101028700 |287     |            26707|        98.0|       0.00|                 0.00|\n|42101028901 |289.01  |            39087|        94.9|       0.00|                 0.00|\n|42101030700 |307     |            58623|        78.5|       0.00|                 0.00|\n|42101033600 |336     |            46191|        55.7|       0.00|                 0.00|\n|42101036501 |365.01  |            83697|        24.3|       0.00|                 0.00|\n|42101008302 |83.02   |            29571|        97.3|       0.00|                 0.00|\n|42101002000 |20      |           106420|        60.2|       0.00|                 0.00|\n|42101025800 |258     |            50813|        94.5|       0.00|                 0.00|\n|42101000701 |7.01    |            90343|        23.0|       0.00|                 0.00|\n|42101038301 |383.01  |            32337|        91.7|       0.00|                 0.00|\n|42101003002 |30.02   |            78843|        55.8|       0.00|                 0.00|\n|42101026800 |268     |            41330|        86.8|       0.00|                 0.00|\n|42101010600 |106     |            19013|        93.0|       0.00|                 0.00|\n|42101015101 |151.01  |            48019|        90.9|       0.00|                 0.00|\n|42101000902 |9.02    |            85271|        31.8|       0.00|                 0.00|\n|42101007800 |78      |            63348|        43.7|       0.00|                 0.00|\n|42101008801 |88.01   |            33990|        46.2|       0.00|                 0.00|\n|42101025400 |254     |            68287|        85.8|       0.00|                 0.00|\n|42101031501 |315.01  |            59738|        60.0|       0.00|                 0.00|\n|42101013300 |133     |            98373|        52.5|       0.00|                 0.00|\n|42101004002 |40.02   |            94150|        27.3|       0.00|                 0.00|\n|42101010700 |107     |            42569|        92.3|       0.00|                 0.00|\n|42101017800 |178     |            42104|        82.2|       0.00|                 0.00|\n|42101031200 |312     |            52211|        90.8|       0.00|                 0.00|\n|42101007101 |71.01   |            44286|        94.0|       0.00|                 0.00|\n|42101000806 |8.06    |           179609|        24.3|       0.00|                 0.00|\n|42101014700 |147     |            26018|        67.4|       0.00|                 0.00|\n|42101020300 |203     |            49115|        97.5|       0.00|                 0.00|\n|42101028300 |283     |            37300|        96.8|       0.00|                 0.00|\n|42101005400 |54      |            56197|        85.5|       0.00|                 0.00|\n|42101007000 |70      |            41206|        98.8|       0.00|                 0.00|\n|42101008602 |86.02   |            32127|        69.0|       0.00|                 0.00|\n|42101013602 |136.02  |           131705|        19.3|       0.00|                 0.00|\n|42101023700 |237     |            68676|        72.2|       0.00|                 0.00|\n|42101026500 |265     |            46806|        95.9|       0.00|                 0.00|\n|42101026600 |266     |            52267|        97.7|       0.00|                 0.00|\n|42101027402 |274.02  |            71551|        92.8|       0.00|                 0.00|\n|42101030501 |305.01  |            50240|        94.7|       0.00|                 0.00|\n|42101031402 |314.02  |            61318|        88.6|       0.00|                 0.00|\n|42101033101 |331.01  |            60333|        55.7|       0.00|                 0.00|\n|42101033500 |335     |            47289|        66.2|       0.00|                 0.00|\n|42101033800 |338     |            67683|        36.7|       0.00|                 0.00|\n|42101036000 |360     |            63170|        49.9|       0.00|                 0.00|\n|42101009500 |95      |            32935|        99.0|       0.00|                 0.00|\n|42101013601 |136.01  |           108867|        21.3|       0.00|                 0.00|\n|42101989300 |9893    |               NA|        78.8|       0.00|                 0.00|\n|42101004104 |41.04   |            62857|        62.2|       0.00|                 0.00|\n|42101013702 |137.02  |            82660|        56.5|       0.00|                 0.00|\n|42101001203 |12.03   |           107537|        20.0|       0.00|                 0.00|\n|42101002200 |22      |            73462|        55.7|       0.00|                 0.00|\n|42101002701 |27.01   |            95224|        42.6|       0.00|                 0.00|\n|42101003702 |37.02   |            47760|        78.6|       0.00|                 0.00|\n|42101035701 |357.01  |            61399|        50.1|       0.00|                 0.00|\n|42101007102 |71.02   |            40602|        97.4|       0.00|                 0.00|\n|42101008102 |81.02   |            53289|        90.1|       0.00|                 0.00|\n|42101008500 |85      |            45747|        86.8|       0.00|                 0.00|\n|42101008701 |87.01   |            61621|        45.7|       0.00|                 0.00|\n|42101013900 |139     |            52741|        69.4|       0.00|                 0.00|\n|42101014900 |149     |            37431|        94.3|       0.00|                 0.00|\n|42101017202 |172.02  |            48229|        99.1|       0.00|                 0.00|\n|42101035702 |357.02  |            64919|        30.5|       0.00|                 0.00|\n|42101020102 |201.02  |            33947|        99.4|       0.00|                 0.00|\n|42101023800 |238     |            66691|        72.6|       0.00|                 0.00|\n|42101024700 |247     |            47849|        94.8|       0.00|                 0.00|\n|42101027000 |270     |            95619|        87.0|       0.00|                 0.00|\n|42101029800 |298     |            47292|        84.8|       0.00|                 0.00|\n|42101030600 |306     |            44108|        63.6|       0.00|                 0.00|\n|42101030900 |309     |            56782|        81.8|       0.00|                 0.00|\n|42101031401 |314.01  |            56818|        62.2|       0.00|                 0.00|\n|42101031700 |317     |            36880|        76.7|       0.00|                 0.00|\n|42101038000 |380     |            57386|        51.9|       0.00|                 0.00|\n|42101011700 |117     |           127083|        55.7|       0.00|                 0.00|\n|42101000404 |4.04    |            93998|        22.2|       0.00|                 0.00|\n|42101000805 |8.05    |            90741|        25.6|       0.00|                 0.00|\n|42101036901 |369.01  |               NA|       100.0|       0.00|                 0.00|\n|42101005600 |56      |            35474|        95.7|       0.00|                 0.00|\n|42101008702 |87.02   |            56181|        37.9|       0.00|                 0.00|\n|42101026000 |260     |            64868|        98.6|       0.00|                 0.00|\n|42101027600 |276     |            65282|        96.9|       0.00|                 0.00|\n|42101028600 |286     |            60892|        97.8|       0.00|                 0.00|\n|42101009000 |90      |            38976|        45.7|       0.00|                 0.00|\n|42101026900 |269     |            69769|        81.0|       0.00|                 0.00|\n|42101014201 |142.01  |           149475|        20.0|       0.00|                 0.00|\n|42101009100 |91      |            35139|        64.7|       0.00|                 0.00|\n|42101035602 |356.02  |           106480|        45.0|       0.00|                 0.00|\n|42101039001 |390.01  |            41296|        96.9|       0.00|                 0.00|\n|42101028500 |285     |               NA|        99.2|       0.00|                 0.00|\n|42101007200 |72      |            50660|        98.4|       0.00|                 0.00|\n|42101008802 |88.02   |            31293|        56.0|       0.00|                 0.00|\n|42101017201 |172.01  |            26313|        99.2|       0.00|                 0.00|\n|42101018802 |188.02  |            47529|        95.8|       0.00|                 0.00|\n|42101036302 |363.02  |            84528|        46.6|       0.00|                 0.00|\n|42101036902 |369.02  |            31635|        47.3|       0.00|                 0.00|\n|42101026301 |263.01  |            67379|        97.8|       0.00|                 0.00|\n|42101003701 |37.01   |            69896|        75.8|       0.00|                 0.00|\n|42101031800 |318     |            65556|        78.8|       0.00|                 0.00|\n|42101002801 |28.01   |            71027|        51.5|       0.09|                 0.02|\n|42101000901 |9.01    |            51384|        46.5|       0.08|                 0.04|\n|42101031101 |311.01  |            51460|        81.6|       0.16|                 0.04|\n|42101009600 |96      |            42297|       100.0|       0.19|                 0.05|\n|42101019800 |198     |            36502|        97.2|       0.32|                 0.05|\n|42101026302 |263.02  |            77160|        98.3|       0.23|                 0.05|\n|42101013200 |132     |            44299|        73.2|       0.22|                 0.06|\n|42101017500 |175     |            30823|        97.3|       0.42|                 0.06|\n|42101003100 |31      |            83620|        64.9|       0.29|                 0.06|\n|42101020000 |200     |            18510|        84.8|       0.08|                 0.06|\n|42101016701 |167.01  |            52656|        96.5|       0.19|                 0.06|\n|42101016901 |169.01  |            38958|        98.9|       0.24|                 0.07|\n|42101012000 |120     |            61483|        72.2|       0.13|                 0.07|\n|42101001900 |19      |           144261|        45.6|       0.28|                 0.08|\n|42101012100 |121     |            53377|        80.4|       0.31|                 0.10|\n|42101030000 |300     |            33419|        87.7|       0.73|                 0.10|\n|42101001101 |11.01   |            61850|        40.4|       0.48|                 0.11|\n|42101013401 |134.01  |           147361|        15.4|       0.35|                 0.12|\n|42101017601 |176.01  |            27006|        95.5|       0.56|                 0.12|\n|42101011000 |110     |            29122|        90.7|       0.37|                 0.12|\n|42101004001 |40.01   |            82258|        26.8|       0.49|                 0.12|\n|42101033300 |333     |            55389|        43.1|       0.52|                 0.13|\n|42101011800 |118     |            35515|        98.8|       0.62|                 0.13|\n|42101015600 |156     |            64125|        70.0|       0.23|                 0.14|\n|42101002802 |28.02   |            94427|        41.0|       0.82|                 0.14|\n|42101037700 |377     |            22621|        65.1|       0.72|                 0.14|\n|42101001600 |16      |           144954|        12.4|       0.35|                 0.14|\n|42101015200 |152     |            42256|        96.2|       1.22|                 0.15|\n|42101014000 |140     |            49234|        62.4|       0.79|                 0.16|\n|42101001301 |13.01   |           133320|        38.1|       0.29|                 0.16|\n|42101010000 |100     |            54871|        94.9|       0.97|                 0.18|\n|42101009801 |98.01   |            75446|        94.0|       0.46|                 0.18|\n|42101020101 |201.01  |            28559|        98.3|       0.66|                 0.18|\n|42101011300 |113     |            44545|        98.7|       0.76|                 0.19|\n|42101019900 |199     |            28803|        99.4|       0.98|                 0.19|\n|42101019502 |195.02  |            28291|       100.0|       0.76|                 0.20|\n|42101007900 |79      |            85018|        45.2|       0.84|                 0.20|\n|42101016702 |167.02  |            34063|        97.6|       0.61|                 0.22|\n|42101009400 |94      |            30335|        99.4|       0.89|                 0.23|\n|42101006300 |63      |            32997|        97.7|       1.01|                 0.23|\n|42101016100 |161     |           102324|        51.4|       1.56|                 0.23|\n|42101016002 |160.02  |           110681|        22.9|       1.02|                 0.23|\n|42101015300 |153     |            30915|        62.3|       1.27|                 0.23|\n|42101004101 |41.01   |            72500|        71.3|       1.34|                 0.24|\n|42101006200 |62      |            48634|        96.8|       1.10|                 0.24|\n|42101010400 |104     |            31063|        95.9|       0.96|                 0.26|\n|42101017900 |179     |            53343|        61.4|       1.48|                 0.26|\n|42101004201 |42.01   |            84500|        40.9|       1.22|                 0.27|\n|42101016902 |169.02  |            22422|       100.0|       1.04|                 0.27|\n|42101028400 |284     |            28236|        93.3|       0.93|                 0.28|\n|42101011900 |119     |            63628|        93.5|       1.31|                 0.28|\n|42101034502 |345.02  |            66557|        55.7|       1.52|                 0.29|\n|42101008400 |84      |            53182|        97.3|       1.61|                 0.30|\n|42101017602 |176.02  |            32523|        97.2|       1.23|                 0.32|\n|42101017702 |177.02  |            29551|        93.4|       1.44|                 0.32|\n|42101001800 |18      |           121719|        27.7|       1.08|                 0.33|\n|42101003901 |39.01   |            59262|        50.5|       2.05|                 0.33|\n|42101018002 |180.02  |            70579|        35.8|       1.74|                 0.35|\n|42101024200 |242     |            46144|        76.4|       1.85|                 0.39|\n|42101034000 |340     |           104488|        44.4|       1.31|                 0.39|\n|42101034501 |345.01  |            47142|        45.8|       1.92|                 0.40|\n|42101008601 |86.01   |            87875|        43.9|       1.37|                 0.41|\n|42101017300 |173     |            26875|        95.2|       1.10|                 0.41|\n|42101036700 |367     |           156638|        31.8|       1.62|                 0.43|\n|42101000101 |1.01    |           108438|        16.4|       0.89|                 0.45|\n|42101000200 |2       |            97256|        55.4|       1.55|                 0.48|\n|42101030200 |302     |            60625|        80.3|       3.85|                 0.50|\n|42101031600 |316     |            42176|        67.4|       2.99|                 0.50|\n|42101003001 |30.01   |            55288|        70.7|       1.99|                 0.53|\n|42101000401 |4.01    |            89663|        52.3|       1.51|                 0.53|\n|42101012203 |122.03  |            63409|        73.8|       0.60|                 0.56|\n|42101000702 |7.02    |            63200|        47.6|       1.17|                 0.57|\n|42101010900 |109     |            31343|        81.4|       1.56|                 0.61|\n|42101001002 |10.02   |           137250|        14.9|       2.13|                 0.61|\n|42101011400 |114     |            44416|        95.2|       4.32|                 0.63|\n|42101020200 |202     |            35000|        98.4|       2.73|                 0.66|\n|42101024000 |240     |            63795|        71.9|       2.64|                 0.67|\n|42101002400 |24      |            84732|        25.7|       3.15|                 0.67|\n|42101001302 |13.02   |           101884|        21.4|       3.14|                 0.67|\n|42101027901 |279.01  |            36135|        99.9|       2.22|                 0.68|\n|42101011100 |111     |            47632|        98.8|       2.71|                 0.68|\n|42101015800 |158     |           116629|        21.6|       5.03|                 0.72|\n|42101001102 |11.02   |           136310|        26.8|       2.12|                 0.72|\n|42101028800 |288     |            57996|        94.0|       3.28|                 0.72|\n|42101015102 |151.02  |            22720|        98.6|       3.66|                 0.74|\n|42101009802 |98.02   |            79531|        95.9|       4.39|                 0.76|\n|42101024500 |245     |            21117|        92.6|       3.73|                 0.76|\n|42101001400 |14      |            98981|        34.3|       3.36|                 0.80|\n|42101025900 |259     |            53713|        97.7|       3.68|                 0.83|\n|42101016400 |164     |            24497|        98.0|       3.50|                 0.85|\n|42101016300 |163     |            39872|        91.2|       2.22|                 0.88|\n|42101013500 |135     |           146792|        20.7|       3.68|                 0.88|\n|42101016600 |166     |            57778|        86.5|       1.71|                 0.88|\n|42101004103 |41.03   |            52083|        80.6|       4.18|                 0.89|\n|42101004202 |42.02   |            75984|        39.3|       4.95|                 0.89|\n|42101010800 |108     |            32999|        93.9|       4.49|                 0.90|\n|42101011200 |112     |            28958|        99.7|       5.64|                 0.91|\n|42101017400 |174     |            35528|        98.8|       2.34|                 0.91|\n|42101032600 |326     |            80283|        50.1|       6.82|                 0.94|\n|42101020400 |204     |            46037|        97.9|       3.48|                 0.94|\n|42101001700 |17      |           145833|        34.7|       2.83|                 0.96|\n|42101013701 |137.01  |            94396|        62.1|       1.81|                 0.96|\n|42101025300 |253     |            55988|        88.8|       4.76|                 1.00|\n|42101032100 |321     |            50409|        65.0|       3.70|                 1.00|\n|42101014100 |141     |            21211|        71.3|       3.30|                 1.05|\n|42101035800 |358     |            63375|        33.3|       6.40|                 1.07|\n|42101014600 |146     |            51563|        65.4|       5.74|                 1.08|\n|42101006700 |67      |            43220|        98.1|       8.45|                 1.09|\n|42101002702 |27.02   |            99797|        25.8|       4.82|                 1.09|\n|42101002100 |21      |           116354|        53.1|       2.79|                 1.10|\n|42101038200 |382     |            44164|        44.5|       2.91|                 1.14|\n|42101019000 |190     |            36857|        86.1|       8.55|                 1.14|\n|42101025200 |252     |            30596|        90.1|       9.62|                 1.14|\n|42101012201 |122.01  |            42782|        79.4|       3.32|                 1.15|\n|42101037900 |379     |            81528|         8.9|       5.68|                 1.16|\n|42101027700 |277     |               NA|        98.1|       6.38|                 1.16|\n|42101014400 |144     |           129023|        41.2|       7.20|                 1.17|\n|42101021700 |217     |            86222|        27.5|       6.74|                 1.19|\n|42101033000 |330     |            65749|        67.6|      12.47|                 1.20|\n|42101024600 |246     |            53414|        85.5|       2.95|                 1.21|\n|42101037600 |376     |           101742|        45.6|       4.10|                 1.26|\n|42101001500 |15      |           108378|        27.5|       3.83|                 1.27|\n|42101002300 |23      |           125781|        27.6|       4.09|                 1.34|\n|42101012204 |122.04  |            46037|        85.7|       5.64|                 1.41|\n|42101018801 |188.01  |            22349|        84.3|       4.91|                 1.44|\n|42101025500 |255     |            78798|        47.9|       4.07|                 1.47|\n|42101036202 |362.02  |            95026|        15.6|       7.90|                 1.47|\n|42101002900 |29      |           104981|        29.5|       5.99|                 1.49|\n|42101020900 |209     |           125064|        27.4|       4.73|                 1.49|\n|42101019501 |195.01  |            25590|        97.9|       7.08|                 1.50|\n|42101020701 |207.01  |           115402|        23.7|       6.28|                 1.51|\n|42101027800 |278     |            33655|        98.6|       8.00|                 1.52|\n|42101003902 |39.02   |            87258|        18.5|       7.99|                 1.53|\n|42101014500 |145     |            42619|        87.9|       3.74|                 1.56|\n|42101014300 |143     |           127520|        18.9|       2.95|                 1.56|\n|42101035900 |359     |            48571|        31.8|       7.59|                 1.59|\n|42101013402 |134.02  |            92500|        20.6|       4.50|                 1.60|\n|42101026200 |262     |            59954|        98.6|       6.65|                 1.62|\n|42101008000 |80      |            70526|        78.0|       6.29|                 1.65|\n|42101024900 |249     |            24904|        99.0|       5.23|                 1.68|\n|42101000801 |8.01    |           130096|        28.3|       2.94|                 1.71|\n|42101003600 |36      |            43688|        87.0|      12.11|                 1.76|\n|42101031502 |315.02  |            45282|        58.4|       6.52|                 1.81|\n|42101031300 |313     |            63241|        84.2|      12.36|                 1.82|\n|42101031102 |311.02  |            62411|        96.0|       8.90|                 1.82|\n|42101008101 |81.01   |            47614|        88.7|       4.80|                 1.82|\n|42101039002 |390.02  |            64733|        93.4|       8.67|                 1.83|\n|42101029300 |293     |            34076|        63.1|       5.69|                 1.88|\n|42101010300 |103     |            32045|        98.9|       4.31|                 1.89|\n|42101016001 |160.01  |           111170|         4.5|       4.76|                 1.91|\n|42101019200 |192     |            13721|        90.3|      15.63|                 1.92|\n|42101015700 |157     |            88125|        47.3|       5.36|                 2.01|\n|42101010500 |105     |            38581|        94.6|       8.29|                 2.02|\n|42101000803 |8.03    |            86538|        19.0|       7.32|                 2.04|\n|42101017701 |177.01  |            37917|        94.8|       6.40|                 2.06|\n|42101003800 |38      |            94538|        13.5|       8.12|                 2.11|\n|42101012501 |125.01  |            82700|        34.9|       4.95|                 2.12|\n|42101001201 |12.01   |           119683|        19.2|       8.89|                 2.16|\n|42101035601 |356.01  |            61939|        34.1|      11.44|                 2.17|\n|42101003200 |32      |            68250|        75.9|       8.39|                 2.18|\n|42101021400 |214     |            82297|        18.9|       7.59|                 2.18|\n|42101030502 |305.02  |            50245|        91.5|      14.85|                 2.19|\n|42101027100 |271     |            60255|        95.3|       5.85|                 2.22|\n|42101002500 |25      |            83508|        37.5|       9.78|                 2.27|\n|42101018001 |180.01  |            59221|        15.9|       5.12|                 2.30|\n|42101000403 |4.03    |           187743|        25.6|       2.41|                 2.31|\n|42101030800 |308     |            59281|        72.3|      10.79|                 2.31|\n|42101023600 |236     |           105491|        49.7|       5.96|                 2.33|\n|42101016500 |165     |               NA|        97.5|       5.07|                 2.34|\n|42101021100 |211     |            92610|        26.2|       6.03|                 2.34|\n|42101030100 |301     |               NA|        89.9|      15.24|                 2.36|\n|42101021200 |212     |           109861|        16.7|       6.52|                 2.36|\n|42101026400 |264     |            63867|        99.6|      13.12|                 2.40|\n|42101010200 |102     |            23750|        99.1|       8.22|                 2.40|\n|42101033701 |337.01  |            48682|        58.4|      15.24|                 2.40|\n|42101033200 |332     |            71691|        57.4|       6.86|                 2.41|\n|42101024800 |248     |            50385|        98.2|       5.17|                 2.45|\n|42101033102 |331.02  |            61373|        39.2|       9.08|                 2.45|\n|42101027200 |272     |            64102|        97.6|      11.00|                 2.48|\n|42101014202 |142.02  |           101488|        31.8|       6.36|                 2.60|\n|42101028200 |282     |            34420|        97.4|      13.59|                 2.65|\n|42101013800 |138     |            63523|        70.3|       5.17|                 2.69|\n|42101013100 |131     |            31924|        69.3|       4.84|                 2.74|\n|42101032000 |320     |            60957|        54.1|      21.27|                 2.76|\n|42101009200 |92      |            54271|        76.8|       9.60|                 2.82|\n|42101021800 |218     |            70354|        43.7|      13.38|                 2.83|\n|42101020600 |206     |            65580|        50.6|       5.83|                 2.86|\n|42101016800 |168     |            27100|        96.5|       9.20|                 2.90|\n|42101032500 |325     |            52342|        53.9|      16.41|                 2.92|\n|42101003300 |33      |            80850|        65.3|      19.92|                 3.04|\n|42101006000 |60      |            44199|        90.0|      18.14|                 3.06|\n|42101038700 |387     |           124792|        22.8|       7.55|                 3.09|\n|42101037200 |372     |            75185|        49.1|      12.29|                 3.12|\n|42101020800 |208     |            71701|        58.5|       8.29|                 3.15|\n|42101036400 |364     |           101094|        20.1|       3.30|                 3.21|\n|42101035301 |353.01  |            90970|        22.7|      16.53|                 3.26|\n|42101016200 |162     |            39009|        88.6|       7.45|                 3.32|\n|42101001001 |10.01   |           114205|        10.3|       9.35|                 3.32|\n|42101021000 |210     |            88924|        20.7|      16.25|                 3.51|\n|42101025700 |257     |            63542|        52.3|      12.38|                 3.51|\n|42101033400 |334     |            55102|        49.8|      19.68|                 3.51|\n|42101028000 |280     |            36463|        99.4|      14.77|                 3.55|\n|42101034100 |341     |            72275|        29.7|      20.31|                 3.56|\n|42101033702 |337.02  |            67557|        42.9|      17.30|                 3.67|\n|42101007400 |74      |            36250|        88.8|      14.19|                 3.85|\n|42101000300 |3       |           102330|        40.1|      16.45|                 3.88|\n|42101034701 |347.01  |            77800|        46.6|      31.15|                 3.98|\n|42101024400 |244     |            53333|        89.7|      12.25|                 4.19|\n|42101034702 |347.02  |            85298|        22.4|      14.46|                 4.34|\n|42101025600 |256     |            87788|        50.9|      12.05|                 4.37|\n|42101028100 |281     |            55313|        89.9|      14.14|                 4.44|\n|42101017100 |171     |            27300|        94.7|      15.73|                 4.50|\n|42101000102 |1.02    |           108203|        14.7|      13.72|                 4.54|\n|42101020500 |205     |               NA|        97.3|      15.99|                 4.73|\n|42101008200 |82      |            35518|        96.6|      38.89|                 4.76|\n|42101006400 |64      |            42469|        95.0|      21.28|                 4.77|\n|42101029000 |290     |            40870|        95.4|      36.82|                 4.77|\n|42101036600 |366     |           168021|        33.8|      11.31|                 4.82|\n|42101035302 |353.02  |            71232|        37.4|      23.75|                 5.04|\n|42101035500 |355     |            69439|        32.6|      39.25|                 5.22|\n|42101005500 |55      |            67063|        93.8|      33.31|                 5.39|\n|42101017000 |170     |            36677|        81.6|      16.02|                 5.41|\n|42101027500 |275     |            61875|        94.8|      24.50|                 5.41|\n|42101029900 |299     |            34487|        91.3|      22.72|                 5.45|\n|42101037800 |378     |            63772|        21.2|      11.58|                 5.54|\n|42101037500 |375     |            78387|        55.9|      20.15|                 5.63|\n|42101019100 |191     |            50238|        85.8|      52.48|                 6.00|\n|42101006100 |61      |            45521|        93.2|      17.69|                 6.01|\n|42101024100 |241     |            18646|        80.3|       9.06|                 6.12|\n|42101014800 |148     |               NA|        97.0|       5.58|                 6.25|\n|42101007700 |77      |            60817|        42.8|      12.02|                 6.62|\n|42101024300 |243     |            56364|        79.5|      28.12|                 6.81|\n|42101032300 |323     |            40300|        72.2|      25.65|                 6.86|\n|42101023100 |231     |           179911|        15.8|       9.69|                 6.86|\n|42101027300 |273     |            42423|        89.6|      41.15|                 7.48|\n|42101035100 |351     |            66523|        30.1|      30.08|                 7.77|\n|42101031900 |319     |            45846|        71.4|      42.64|                 7.77|\n|42101034900 |349     |            54689|        66.2|      43.51|                 7.93|\n|42101036502 |365.02  |            85750|        20.7|      35.83|                 8.12|\n|42101018400 |184     |            73478|         8.1|      18.54|                 8.16|\n|42101034801 |348.01  |            64608|        23.2|      37.70|                 8.28|\n|42101032900 |329     |            57571|        63.9|      30.09|                 8.28|\n|42101038900 |389     |            66705|        92.1|      27.92|                 8.62|\n|42101008301 |83.01   |            35174|        96.2|      33.63|                 8.71|\n|42101034802 |348.02  |            56032|        40.1|      49.97|                 8.82|\n|42101036201 |362.01  |            93300|        15.8|      50.08|                 9.47|\n|42101034400 |344     |           118397|        28.9|      78.56|                 9.88|\n|42101036301 |363.01  |            82596|        44.2|      37.27|                 9.95|\n|42101021500 |215     |           121667|        30.6|      42.61|                10.75|\n|42101021600 |216     |           101075|        28.2|      26.24|                10.77|\n|42101020702 |207.02  |           192727|        30.2|      25.77|                11.43|\n|42101028902 |289.02  |            38775|        95.7|      67.60|                11.73|\n|42101029100 |291     |            26290|        98.3|      50.15|                12.56|\n|42101038500 |385     |           124324|        16.2|      23.82|                12.61|\n|42101036203 |362.03  |            85733|        17.7|      62.43|                12.85|\n|42101027902 |279.02  |            44509|        72.0|      66.02|                13.29|\n|42101006500 |65      |            48173|        98.5|      64.67|                13.36|\n|42101034200 |342     |            66692|        33.1|      47.89|                13.60|\n|42101012502 |125.02  |           109602|        34.6|      54.26|                13.87|\n|42101036303 |363.03  |           100857|        19.3|     110.41|                16.25|\n|42101023500 |235     |            94904|        41.1|      17.32|                16.51|\n|42101035200 |352     |            88663|        14.9|      81.66|                18.06|\n|42101029200 |292     |            77816|        78.8|      72.39|                18.19|\n|42101036100 |361     |           105208|        32.6|      78.42|                19.93|\n|42101038800 |388     |           113343|        38.4|      80.34|                20.13|\n|42101033900 |339     |            58660|        47.1|      67.52|                21.25|\n|42101039100 |391     |            24963|       100.0|      58.85|                22.70|\n|42101021900 |219     |            78542|        19.2|      41.04|                26.17|\n|42101034803 |348.03  |            78224|        19.3|      99.95|                27.63|\n|42101023900 |239     |            45294|        72.7|      53.98|                29.79|\n|42101022000 |220     |            94750|        25.5|      46.33|                31.75|\n|42101037300 |373     |           113636|        16.7|     348.60|                58.28|\n|42101038100 |381     |            39939|        55.4|      42.51|                59.62|\n|42101038400 |384     |           116250|        27.4|     312.92|               124.77|\n|42101038600 |386     |           180000|        29.6|     219.70|               146.76|\n|42101989100 |9891    |               NA|        90.8|     223.54|               180.28|\n|42101980200 |9802    |               NA|        42.7|    1214.35|              3066.55|\n|42101980100 |9801    |           108889|         4.7|    1331.41|              4452.86|\n|42101980500 |9805    |               NA|          NA|      90.07|                   NA|\n|42101980903 |9809.03 |               NA|          NA|       0.00|                   NA|\n|42101980600 |9806    |               NA|          NA|       0.00|                   NA|\n|42101980003 |9800.03 |               NA|          NA|       0.00|                   NA|\n|42101980902 |9809.02 |               NA|          NA|       0.00|                   NA|\n|42101980906 |9809.06 |               NA|          NA|       0.00|                   NA|\n|42101980905 |9809.05 |               NA|          NA|       0.00|                   NA|\n|42101980904 |9809.04 |               NA|          NA|       0.15|                   NA|\n|42101980901 |9809.01 |               NA|          NA|      39.96|                   NA|\n|42101980701 |9807.01 |               NA|          NA|       0.00|                   NA|\n|42101980300 |9803    |               NA|          NA|      91.00|                   NA|\n|42101980400 |9804    |               NA|          NA|       0.82|                   NA|\n|42101980001 |9800.01 |               NA|          NA|     750.55|                   NA|\n|42101989200 |9892    |               NA|          NA|       0.00|                   NA|\n|42101980702 |9807.02 |               NA|          NA|       0.00|                   NA|\n|42101980002 |9800.02 |               NA|          NA|    1444.52|                   NA|\n|42101980800 |9808    |               NA|          NA|     511.63|                   NA|\n\n\n:::\n\n```{.r .cell-code}\n# Green Acess for vulnerable tracts\nincome_shredhold <- quantile(tracts_analysis$med_hh_income, probs = 0.25, na.rm = TRUE)\nrace_shredhold <- quantile(tracts_analysis$pct_nonwhite, probs = 0.75, na.rm = TRUE)\n\ntracts_analysis <- tracts_analysis %>%\n  mutate(\n    low_income = if_else(med_hh_income < income_shredhold, TRUE, FALSE),\n    high_nonwhite = if_else(pct_nonwhite > race_shredhold, TRUE, FALSE),\n    vulnerable = low_income & high_nonwhite\n  )\nvulnerable_tracts <- tracts_analysis %>%\n  filter(vulnerable)\nvulnerable_tracts %>%\n  st_drop_geometry() %>%\n  select(GEOID, NAME, med_hh_income, pct_nonwhite, park_access_pct, park_acres_per_1000) %>%\n  mutate(\n    med_hh_income = round(med_hh_income, 0),\n    pct_nonwhite = round(pct_nonwhite, 1),\n    park_access_pct = round(park_access_pct, 1),\n    park_acres_per_1000 = round(park_acres_per_1000, 2)\n  ) %>%\n  arrange(park_access_pct, park_acres_per_1000) %>%\n  knitr::kable(\n    caption = \"Vulnerable Census Tracts and Their Green Space Indicators\",\n    col.names = c(\"GEOID\", \"Tract\", \"Median HH Income\", \"% Non-White\", \"Park Access %\", \"Park Acres per 1,000\")\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Vulnerable Census Tracts and Their Green Space Indicators\n\n|GEOID       |Tract  | Median HH Income| % Non-White| Park Access %| Park Acres per 1,000|\n|:-----------|:------|----------------:|-----------:|-------------:|--------------------:|\n|42101005600 |56     |            35474|        95.7|          73.7|                 0.00|\n|42101039001 |390.01 |            41296|        96.9|          89.2|                 0.00|\n|42101028901 |289.01 |            39087|        94.9|          96.9|                 0.00|\n|42101029100 |291    |            26290|        98.3|          97.7|                12.56|\n|42101028700 |287    |            26707|        98.0|          98.9|                 0.00|\n|42101019700 |197    |            32063|        98.0|         100.0|                 0.00|\n|42101006600 |66     |            27206|        94.7|         100.0|                 0.00|\n|42101009300 |93     |            40933|        96.3|         100.0|                 0.00|\n|42101008302 |83.02  |            29571|        97.3|         100.0|                 0.00|\n|42101028300 |283    |            37300|        96.8|         100.0|                 0.00|\n|42101007000 |70     |            41206|        98.8|         100.0|                 0.00|\n|42101009500 |95     |            32935|        99.0|         100.0|                 0.00|\n|42101007102 |71.02  |            40602|        97.4|         100.0|                 0.00|\n|42101020102 |201.02 |            33947|        99.4|         100.0|                 0.00|\n|42101017201 |172.01 |            26313|        99.2|         100.0|                 0.00|\n|42101009600 |96     |            42297|       100.0|         100.0|                 0.05|\n|42101019800 |198    |            36502|        97.2|         100.0|                 0.05|\n|42101017500 |175    |            30823|        97.3|         100.0|                 0.06|\n|42101016901 |169.01 |            38958|        98.9|         100.0|                 0.07|\n|42101017601 |176.01 |            27006|        95.5|         100.0|                 0.12|\n|42101011800 |118    |            35515|        98.8|         100.0|                 0.13|\n|42101015200 |152    |            42256|        96.2|         100.0|                 0.15|\n|42101020101 |201.01 |            28559|        98.3|         100.0|                 0.18|\n|42101019900 |199    |            28803|        99.4|         100.0|                 0.19|\n|42101019502 |195.02 |            28291|       100.0|         100.0|                 0.20|\n|42101016702 |167.02 |            34063|        97.6|         100.0|                 0.22|\n|42101009400 |94     |            30335|        99.4|         100.0|                 0.23|\n|42101006300 |63     |            32997|        97.7|         100.0|                 0.23|\n|42101010400 |104    |            31063|        95.9|         100.0|                 0.26|\n|42101016902 |169.02 |            22422|       100.0|         100.0|                 0.27|\n|42101017602 |176.02 |            32523|        97.2|         100.0|                 0.32|\n|42101017300 |173    |            26875|        95.2|         100.0|                 0.41|\n|42101020200 |202    |            35000|        98.4|         100.0|                 0.66|\n|42101027901 |279.01 |            36135|        99.9|         100.0|                 0.68|\n|42101015102 |151.02 |            22720|        98.6|         100.0|                 0.74|\n|42101016400 |164    |            24497|        98.0|         100.0|                 0.85|\n|42101011200 |112    |            28958|        99.7|         100.0|                 0.91|\n|42101017400 |174    |            35528|        98.8|         100.0|                 0.91|\n|42101019501 |195.01 |            25590|        97.9|         100.0|                 1.50|\n|42101027800 |278    |            33655|        98.6|         100.0|                 1.52|\n|42101024900 |249    |            24904|        99.0|         100.0|                 1.68|\n|42101010300 |103    |            32045|        98.9|         100.0|                 1.89|\n|42101010500 |105    |            38581|        94.6|         100.0|                 2.02|\n|42101017701 |177.01 |            37917|        94.8|         100.0|                 2.06|\n|42101010200 |102    |            23750|        99.1|         100.0|                 2.40|\n|42101028200 |282    |            34420|        97.4|         100.0|                 2.65|\n|42101016800 |168    |            27100|        96.5|         100.0|                 2.90|\n|42101028000 |280    |            36463|        99.4|         100.0|                 3.55|\n|42101017100 |171    |            27300|        94.7|         100.0|                 4.50|\n|42101008200 |82     |            35518|        96.6|         100.0|                 4.76|\n|42101029000 |290    |            40870|        95.4|         100.0|                 4.77|\n|42101008301 |83.01  |            35174|        96.2|         100.0|                 8.71|\n|42101028902 |289.02 |            38775|        95.7|         100.0|                11.73|\n|42101039100 |391    |            24963|       100.0|         100.0|                22.70|\n\n\n:::\n\n```{.r .cell-code}\n# Green Space Walking Access in Vulnerable Census Tracts\nggplot() +\n  geom_sf(data = tracts_analysis, fill = \"grey95\", color = \"white\", linewidth = 0.15) +\n  geom_sf(data = tracts_analysis %>% filter(vulnerable),\n          aes(fill = park_access_pct), color = \"grey20\", linewidth = 0.2) +\n  scale_fill_viridis_c(option = \"rocket\", na.value = \"grey80\") +\n  labs(\n    title = \"Green Space Walking Access in Vulnerable Census Tracts\",\n    subtitle = \"Vulnerable = low-income and high non-white\",\n    fill = \"Park Access %\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Park Acreage per 1,000 Residents in Vulnerable Census Tracts\nggplot() +\n  geom_sf(data = tracts_analysis %>% filter(!vulnerable),fill = \"grey95\",color = \"white\",linewidth = 0.15) +\n  geom_sf(data = tracts_analysis %>% filter(vulnerable),aes(fill = park_acres_per_1000),color = \"grey80\",linewidth = 0.2) +\n  scale_fill_viridis_c(option = \"plasma\",na.value = \"grey80\") +\n  labs(\n    title = \"Park Acreage per 1,000 Residents in Vulnerable Census Tracts\",\n    subtitle = \"Vulnerable = low-income and high non-white\",\n    fill = \"Acres / 1,000\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Park Walking Access Vulnerable Census Tracts vs Non-vulnerable Census Tracts\nincome_q25 <- unname(quantile(tracts_analysis$med_hh_income, 0.25, na.rm = TRUE))\naccess_median <- median(tracts_analysis$park_access_pct, na.rm = TRUE)\n\ntracts_analysis <- tracts_analysis %>%\n  mutate(\n    low_income = !is.na(med_hh_income) & med_hh_income < income_q25,\n    high_nonwhite_75 = !is.na(pct_nonwhite) & pct_nonwhite > 75,\n    vulnerable = low_income & high_nonwhite_75\n  )\n\nplot_df <- tracts_analysis %>%\n  st_drop_geometry() %>%\n  mutate(\n    vuln_label = if_else(\n      vulnerable,\n      \"Vulnerable tract\",\n      \"Non-vulnerable tract\",\n      missing = \"Non-vulnerable tract\"\n    )\n  ) %>%\n  filter(!is.na(park_access_pct), !is.na(med_hh_income))\n\nggplot(plot_df, aes(x = park_access_pct, y = med_hh_income)) +\n  geom_point(aes(shape = vuln_label), alpha = 0.7, size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 0.8) +\n  geom_hline(yintercept = income_q25, linetype = \"dashed\", linewidth = 0.5) +\n  geom_vline(xintercept = access_median, linetype = \"dashed\", linewidth = 0.5) +\n  labs(\n    title = \"Park Walking Access Vulnerable vs Non-vulnerable\",\n    subtitle = \"Vulnerable = low-income AND >75% non-white\",\n    x = \"Park Access (%)\",\n    y = \"Median Household Income (ACS)\",\n    shape = \"Tract Type\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# Park Acreage per 1,000 Residents Vulnerable Census Tracts vs Non-vulnerable Census Tracts\nincome_q25 <- unname(quantile(tracts_analysis$med_hh_income, 0.25, na.rm = TRUE))\ntracts_analysis <- tracts_analysis %>%\n  mutate(\n    low_income = !is.na(med_hh_income) & med_hh_income < income_q25,\n    high_nonwhite_75 = !is.na(pct_nonwhite) & pct_nonwhite > 75,\n    vulnerable = low_income & high_nonwhite_75\n  )\nplot_df2 <- tracts_analysis %>%\n  st_drop_geometry() %>%\n  mutate(\n    vuln_label = if_else(\n      vulnerable,\n      \"Vulnerable tract\",\n      \"Non-vulnerable tract\",\n      missing = \"Non-vulnerable tract\"\n    )\n  ) %>%\n  filter(!is.na(park_acres_per_1000), !is.na(med_hh_income))\n\nx_p98 <- quantile(plot_df2$park_acres_per_1000, 0.98, na.rm = TRUE)\n\nplot_df2_trim <- plot_df2 %>%\n  filter(park_acres_per_1000 <= x_p98)\n\nggplot(plot_df2_trim, aes(x = park_acres_per_1000, y = med_hh_income)) +\n  geom_point(aes(shape = vuln_label), alpha = 0.7, size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, linewidth = 0.8) +\n  labs(\n    title = \"Park Acreage per 1,000 Residents Vulnerable vs Non-vulnerable\",\n    subtitle = \"Vulnerable = low-income AND >75% non-white; top 2% park acreage values removed for readability\",\n    x = \"Park Acres per 1,000 Residents\",\n    y = \"Median Household Income (ACS)\",\n    shape = \"Tract Type\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-19-4.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nIn this study, census tracts were defined as vulnerable if they were in the lowest 25% of citywide household income and had a non-white population share above 75%. Green space conditions were measured by park walking access and park acreage per 1,000 residents. The results show that, at the tract level, the differences between vulnerable and non-vulnerable tracts are not obvious for these two indicators. Park access in vulnerable tracts is still generally high, and almost all values are above 75%. Park acreage per 1,000 residents is mostly in a lower range, around 0 to 10 acres, and it does not show a clear or stable separation from non-vulnerable tracts. Even after adjusting the vulnerability definition or the green space thresholds, the overall conclusion did not change much. However, this study only focuses on Philadelphia. This result may be related to the city’s stronger attention to green space equity, so it should not be treated as a general conclusion.\n\n## Finally - A few comments about your incorporation of feedback!\n\nBased on the feedback from the previous assignment, I reduced my use of head() and print(), and used kable() instead when showing tables. I also hid some unnecessary outputs so the document is cleaner. Compared with last time, I ran into more errors and technical issues during the spatial analysis, and I asked GPT for help. However, I tried to understand and revise the AI-generated code myself, and I hope the final results are correct.\n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}